### ISSUE TITLE
>>> Appearing in timeline

### ISSUE THREAD

**Issue by atomicules** [oysttyer/oysttyer#1]
[Reported 2014-02-15](https://twitter.com/kyhwana/status/434525389113683968). 

Could be a none issue?

Must be due to [these lines of code](https://github.com/atomicules/TTYtter/blob/b3d254bee9a3ad0b74b8af16e5496cdbb8e271e7/ttytter.pl#L5402-L5505) and according to the [linked](https://github.com/atomicules/TTYtter/blob/b3d254bee9a3ad0b74b8af16e5496cdbb8e271e7/ttytter.pl#L5409) streaming API docs for [public stream messages](https://dev.twitter.com/docs/streaming-apis/messages):

> Blank lines
> 
> On slow streams, some messages may be blank lines which serve as "keep-alive" signals to prevent clients and other network infrastructure from assuming the stream has stalled and closing the connection.

So perhaps it's just that? Not sure why this is a new thing though?

If it is this, then perhaps TTYtter should hide these keep-alives?

**Comment by jasonwryan** [comment]
I started noticing these over the weekend. They are definitely more pronounced on my home connection (which is, by international standards, quite slow), but I am also seeing them at work where we have a 20Mbps connection.

Hiding them would be a good idea...

I should note, I use "pause=180" in my rc.

**Comment by atomicules** [comment]
I'm going to try and have a look at this (but if any one more clever than me wants to have a go, please feel free).

**Comment by atomicules** [comment]
Been doing a bit of debugging. Added the following above line [5873](https://github.com/atomicules/TTYtter/blob/b3d254bee9a3ad0b74b8af16e5496cdbb8e271e7/ttytter.pl#L5873):

```
print $streamout Dumper($event_ref);
```

and I'm seeing this:

```
$VAR1 = {

 'source' => {},
 'status_withheld' => {
    'withheld_in_countries' => [],
    'user_id' => XXXXXXXX,
    'id' => 'X.XXXXXXXXXXXXXXXXXe+17'
}
};
>>> 
```

So perhaps not what I first thought, but gives me something further to investigate.

**Comment by atomicules** [comment]
Aha! https://dev.twitter.com/discussions/26130

Getting somewhere. Wonder if this is just temporary a glitch on Twitter's end?

**Comment by jasonwryan** [comment]
Nice find. Hopefully, Twitter will provide an explanation...

**Comment by IvanSanchez** [comment]
This is caused by TTYtter's default handling of events.
These should help: https://github.com/IvanSanchez/ttytter-extensions/blob/master/debug_event_handle.pl https://github.com/IvanSanchez/ttytter-extensions/blob/master/withheld.pl

**Comment by jasonwryan** [comment]
Seems to be fixed (at least at the moment). I won't take [any credit for it](https://twitter.com/jasonwryan/status/435880282919428096)... (thanks to Ivan for the withheld extension).

**Comment by atomicules** [comment]
It seems to be quite intermittent for me. Thought about putting something like this in:

``` perl
sub defaulteventhandle {
    (&flag_default_call, return) if ($multi_module_context);
    my $event_ref = shift;
    # in this version, we silently filter delete events, but your
    # extension would still get them delivered.
    return 1 if ($event_ref->{'delete'});
    # Also silently filter status_withheld with no countries listed
    if ($event_ref->{'status_withheld'}) {
        if (scalar(@{$event_ref->{'status_withheld'}->{'withheld_in_countries'}}) == 0) {
            return 1;
        }
    }
    print $streamout &standardevent($event_ref);
    return 1;
}
```

but the issue has disappeared for me before I can test.

**Comment by atomicules** [comment]
Also, there does seem to be intent for handling `status_withheld` in ttytter already. See line [5472](https://github.com/atomicules/TTYtter/blob/master/ttytter.pl#L5472)

**Comment by IvanSanchez** [comment]
I have been trying to extend withheld.pl to prevent the default handler from running, with no avail. Will try to give it another shot tomorrow, or maybe I can make a pull request to change the default event handler.

**Comment by atomicules** [comment]
Looks like the issue has been resolved on Twitter's end? I'm not seeing these any more.

**Comment by IvanSanchez** [comment]
"Twitter not sending more withheld events" doesn't mean "TTYtter handles withheld events properly" :-/

**Comment by atomicules** [comment]
Oh yeah, for sure, completely agree. It just means that now the issue of "status_withheld with no countries listed" has gone away, it's much harder to test a fix for it.

**Comment by atomicules** [comment]
What about that as a potential fix/improvement?

I think the problem was with the [original code](https://github.com/atomicules/TTYtter/blob/master/ttytter.pl#L5472-L5479) was that as [commented](https://github.com/atomicules/TTYtter/blob/master/ttytter.pl#L5473) `id_str` isn't actually available and so this bit of code never executed.

But as mentioned above I don't know anyway of testing this because I'm not seeing any status_withheld messages currently.

**Comment by IvanSanchez** [comment]
I'd rather also show withheld tweets even if the countries array is empty. At least that's what I was seeing in my timeline.

**Comment by atomicules** [comment]
Hmm, but when I was seeing this issue, I was seeing the "Withheld tweet" message for tweets that were actually appearing in my timeline. I.e. it was my understanding that "status_withheld with no countries listed" was a temporary bug/glitch in the API.

**Comment by funnelfiasco** [comment]
This has been around for a year and a half (has it really been that long?) with no updates and it's not clear that it's still an issue, so I'm going to call this closed. If someone wants to take a look at it again later, feel free to reopen.
