### ISSUE TITLE
untrack words or chars

### ISSUE THREAD

**Issue by makkanx** [oysttyer/oysttyer#100]
I track some words but I get a lot of tweets in Turkish which I'm completely uninterested in.
I would like to be able to untrack words or char.
Right now I'm using filterusers but the list is getting long.

**Comment by funnelfiasco** [comment]
I think `-filter=[Perl expression]` will get what you want. If I understand, you want (as an example) to track the word "coffee" but not see "Turkish coffee" (perhaps you don't like the sludge at the bottom. That's your choice). You would use: `-filter="/turkish/i && /coffee/"`. 

There's more description in the [TTYtter documentation](http://www.floodgap.com/software/ttytter/copts.html), which I really need to work on updating for oysttyer.

**Comment by makkanx** [comment]
How would I then add a second set?  "|" inbetween or?
-filter="/turkish/i && /coffee/ | /english/i && /coffee/"

**Comment by classilla** [comment]
> How would I then add a second set?  "|" inbetween or?
> -filter="/turkish/i && /coffee/ | /english/i && /coffee/"

Try
-filter="(/turkish/i && /coffee/) || (/english/i && /coffee/)"
