### ISSUE TITLE
Allow /open to open tweets

### ISSUE THREAD

**Issue by Azenet** [oysttyer/oysttyer#101]
Hi,

Currently when trying to `/open` a tweet that contains no links will say that the tweet contains no links, which is good, however it would be nice to have a toggle so that `/open`-ing a tweet that has no links just opens the tweet itself. As a "workaround" I am using `/dump id` then `/open` at the moment.

**Comment by funnelfiasco** [comment]
Great idea. I've done the same myself from time to time. I think we'll want it to be a separate command (open to bikeshedding on what we call it). This makes it explicitly clear what you want to do.

**Comment by Llammissar** [comment]
This is tough because /url is taken; that'd be the obvious one, IMO.  Maybe /id?  /info? m#^/t(weet)?i(nfo)?#... 

Oh, /web!  Or I suppose /address works too, but that's long and it looks like we already have an /add command as a complete initial substring.

**Comment by funnelfiasco** [comment]
I have a branch ([feature/issue101](https://github.com/oysttyer/oysttyer/tree/feature/issue101)) that adds this functionality with the `/web` command if anyone wants to try it out. I'll merge it in if it doesn't blow up horribly.

**Comment by funnelfiasco** [comment]
Okay, I merge my branch and pushed it to master.
