### ISSUE TITLE
/doesfollow not working for other users

### ISSUE THREAD

**Issue by tjharman** [oysttyer/oysttyer#102]
Maybe this is now a Twitter limitation?

I can check who I follow:
```
tjh> /doesfollow tjh wwesubway <025
--- does tjh follow wwesubway? => true
```
But I can't check who someone else follows anymore:

Does subway_nz follow wwwsubway?
```
tjh> /doesfollow subway_nz wwesubway <031
-- sorry, bogus server response, try again later.
```
Ok, does subway_nz follow me (tjh)?
```
tjh> /doesfollow subway_nz tjh <025
-- sorry, bogus server response, try again later.
```

**Comment by vitusson** [comment]
Nope, Works like it should for me
Maybe you should just check if usernames are right before reporting? ;-)
/whois subway_nz 
Nothing happens. There is no such user....
/whois subwaynz
Subway New Zealand (subwaynz) (f:749/8726) (u:5193) (Verified) 
URL:		http://t.co/ldECYaifEO
Location:	New Zealand
Picture:	http://pbs.twimg.com/profile_images/648256925646229505/HhVxmy4j_normal.jpg

/doesfollow wwesubway subwaynz <030   
--- does wwesubway follow subwaynz? => false

**Comment by tjharman** [comment]
Ugh, I am SUCH an (embarrassed) idiot.
