### ISSUE TITLE
one-liner option

### ISSUE THREAD

**Issue by Jzarecta** [oysttyer/oysttyer#104]
is there a way to tweet without starting the session, only tweet one at a time as a one-liner option?

**Comment by funnelfiasco** [comment]
There is! `oysttyer.pl -status="Check out all of these thoughts I am leading."`

There are some partial docs at http://oysttyer.github.io/docs/userGuide.html and the TTYtter docs are still mostly applicable http://www.floodgap.com/software/ttytter/
