### ISSUE TITLE
Uparrow not working

### ISSUE THREAD

**Issue by makkanx** [oysttyer/oysttyer#105]
After reinstalling my machine oysttyer is not completely working. Uparrow is not working so I can't get the latest used command again. What am I missing?

**Comment by funnelfiasco** [comment]
You'll need the `Term::ReadLine::TTYtter` CPAN package: http://search.cpan.org/~ckaiser/Term-ReadLine-TTYtter-1.4/ (and make sure you have `readline=1` in your .oysttyerrc)
