### ISSUE TITLE
Share a tweet through a DM

### ISSUE THREAD

**Issue by atomicules** [oysttyer/oysttyer#11]
As per [this announcement](https://blog.twitter.com/2014/share-a-tweet-through-direct-messages).

So I guess we want some way to say something like `/dm a1 @someone Look at this tweet` where a1 is the reference to the tweet.

**Comment by funnelfiasco** [comment]
I have a change inbound to implement this with a new command. Not quite as slick as using the `/dm` command, but it's functional, at least. I'm open to improvements.
