### ISSUE TITLE
Shortened URL is not stored in %URL%

### ISSUE THREAD

**Issue by ghost** [oysttyer/oysttyer#112]
Don't remember if the behaviour has changed, but in my opinion, the output of the shortener should be saved in %URL% for reuse. Now the variable is empty.

```
oysttyer> /sh https://github.com/oysttyer/oysttyer/ <024
*** shortened to: https://is.gd/Rdcy6t
oysttyer> %URL% <005
(expanded to "")
oysttyer>  <000
```

**Comment by funnelfiasco** [comment]
Added a fix for this into the forthcoming 2.8.2.
