### ISSUE TITLE
sysread() is deprecated on :utf8 handles

### ISSUE THREAD

**Issue by jasonwryan** [oysttyer/oysttyer#115]
With the upgrade to Perl 5.26, oysttyer now throws a warning while tweeting:

```
sysread() is deprecated on :utf8 handles. This will be a fatal error in Perl 5.30 at Scripts/oysttyer.pl line 6471.                                            
sysread() is deprecated on :utf8 handles. This will be a fatal error in Perl 5.30 at Scripts/oysttyer.pl line 4267. 
```

**Comment by funnelfiasco** [comment]
Thanks for the report. Some quick testing suggests replacing `sysread` with `read` fixes it. I'll test on it a little further and if everything still seems to work, I'll push a branch for others to test again.

**Comment by funnelfiasco** [comment]
Okay, I lied. It's functional, but seems to break the prompt. I'll have to look into it more.

**Comment by classilla** [comment]
> Okay, I lied. It's functional, but seems to break the prompt. I'll have to look into it more.

Spitballing here, you could probably do a mass change from `sysread()` to
`read()` and I don't think much would break at this point since all that
the IPC communication sends back and forth is 7-bit bytes (anything that
could be Unicode or UTF-8 is separately encoded). I haven't tried this,
though.

For the record I think the change is stupid since sysread() and syswrite()
were never intended to be safe, so a safety change is pointless. However,
intelligence does not appear to be a baseline attribute for the Perl 5
maintainers these days.

**Comment by classilla** [comment]
Derp derp, I see that's exactly what you were talking about. How does it break the prompt, exactly?

**Comment by funnelfiasco** [comment]
In the way that if I had installed `Term::ReadLine::TTYtter` in my perlbrew environment, it would be working just fine TYVM. :-/

(which is to say: it's user error)

**Comment by funnelfiasco** [comment]
Okay, new branch if anyone wants to do some additional verification: https://github.com/oysttyer/oysttyer/tree/bugfix/sysread-issue115

Works for me on Perl 5.26 and Perl 5.24.

**Comment by knghtbrd** [comment]
This issue ought to be reopened since, as of 2.9.1, the deprecation warnings are there once again.

**Comment by funnelfiasco** [comment]
I can't reproduce this on my Fedora 28 box with Perl 5.26. There are still a few sysreads in the code, but I haven't seen deprecation warnings since 2.9.0. Can you provide more context? Do you see it at launch or during use?

**Comment by knghtbrd** [comment]
No, strangely one showed up at startup before, but it doesn't show at
startup now.  Weird.  Ignore me for now.  I'll keep this around and if I
see it again I'll see if I can figure out which sysread is doing it.

Joseph
