### ISSUE TITLE
Check if ttytter is up-to-date using github releases

### ISSUE THREAD

**Issue by IvanSanchez** [oysttyer/oysttyer#12]
TTYtter should be able to visit https://github.com/atomicules/TTYtter/releases (or use the github API) to check if the running version is the latest version available, in a similar fashion floodgap's TTYtter was doing.

**Comment by atomicules** [comment]
Yeah, it should. I wrote some brief thoughts here: https://github.com/atomicules/TTYtter/commit/81e13f99e1151d63f0c66995cc1143fd26920ac5

I think what I'll do is work on the multiple image support milestone first and then add in the update checking. That way I'll have a bit more confidence I can actually maintain this.
