### ISSUE TITLE
Problem Running on Windows

### ISSUE THREAD

**Issue by Suleman-Elahi** [oysttyer/oysttyer#121]
When I run the specified command on Windows 10, following error is raised;

+=======================================================+
-- using SSL for default URLs.
trying to find cURL ... not found.
failed. trying to find Lynx ... not found.
you must have either Lynx or cURL installed to use oysttyer.
+========================================================+

**Comment by funnelfiasco** [comment]
Do you have cURL installed? If not, you'll need to install it first. You can download cURL for Windows at https://curl.haxx.se/download.html
