### ISSUE TITLE
Using `synch` hangs 2.9.0

### ISSUE THREAD

**Issue by funnelfiasco** [oysttyer/oysttyer#123]
This is a regression from 2.8.0. If using `synch`, you'll never get beyond the loading screen.

Reported by [JudeDaShiell](https://twitter.com/JudeDaShiell)

**Comment by funnelfiasco** [comment]
Well it looks like the offending change was replacing `sysread()` with `read()` to address #115. I'm going to have to dig into the differences more and see what I can do about it.

**Comment by funnelfiasco** [comment]
Here's what I've been able to figure out so far:

When using `-synch`, it hangs at the second time through [line 4217](https://github.com/oysttyer/oysttyer/blob/2.9.0/oysttyer.pl#L4217). Throwing some debug prints in there, I get:

```DEBUG rout:  rin:
DEBUG rout =
<<<the select happened here>>>
DEBUG nfound is 1
DEBUG rout: synm---------------
 rin:
<<<the select happened here>>>
<<<keep waiting, nothing will ever happen>>>
```

From what I can tell (and this is admittedly beyond my depth), the issue is that `sysread()` is non-buffering and `read()` is buffering and that `select()` works with `sysread()` but not really with `read()`. 

We have to keep UTF-8 support (Twitter without emoji? perish the thought!), which means we can't revert back to using `sysread()`, at least not in the long term. It looks like maybe we can fake our way around it with `IO::Select`? I'm open to (read: begging for) help on this one.

**Comment by classilla** [comment]
> From what I can tell (and this is admittedly beyond my depth), the issue is that `sysread()` is non-buffering and `read()` is buffering and that `select()` works with `sysread()` but not really with `read()`. 

That is indeed essentially the problem. There is another solution, which should mostly just work: take :utf8 off the IPC filehandles P and W (under `initialize our route back out`) and make sure all transmissions over them are hex-coded. This is already the case for tweet text, and the screen names should be 7-bit, so they don't need to be encoded. Then you can just keep using sysread(). I haven't tried this, but my gut suggests this should mostly work with possibly a few gaps to plug.

**Comment by classilla** [comment]
(er, you can keep using `sysread()` for `P` and `W`; the rest should stay `read()` if `:utf8` was set on those handles.)

**Comment by classilla** [comment]
Oh, and do the same for filehandle `C`, which is actually where the synch opcode is being sent.

**Comment by funnelfiasco** [comment]
Great, thanks for the suggestion. I'll give it a try and we'll see how that goes.

**Comment by funnelfiasco** [comment]
@classilla I think I did as you suggested in [this branch](https://github.com/oysttyer/oysttyer/blob/bugfix/issue123-synch/oysttyer.pl) but the synch behavior persists. It looks like I've removed the `:utf8` from `C`, `P`, and `W` and changed them all back to `sysread()`.

**Comment by classilla** [comment]
> @classilla I think I did as you suggested in [this branch](https://github.com/oysttyer/oysttyer/blob/bugfix/issue123-synch/oysttyer.pl) but the synch behavior persists. It looks like I've removed the `:utf8` from `C`, `P`, and `W` and changed them all back to `sysread()`.

`if(read(STDIN, $rout, 20) != 20) {` at line 4328 should also be `sysread()`

**Comment by funnelfiasco** [comment]
@classilla changing that line fixes the `synch` behavior, but it re-introduces the deprecation warnings.

I thought that if we don't set `:utf8` on `STDIN` on line 4111, that would fix the errors, but that does not seem to be the case. I also expected that it would mean users will not be able to use unicode characters in tweets, but that's also wrong. So perhaps 4111 is not where line 4328's `STDIN` gets the `:utf8` setting? Is `STDIN` there only used to receive commands and not actual user input?

**Comment by classilla** [comment]
> @classilla changing that line fixes the `synch` behavior, but it re-introduces the deprecation warnings.
> 
> I thought that if we don't set `:utf8` on `STDIN` on line 4111, that would fix the errors, but that does not seem to be the case. I also expected that it would mean users will not be able to use unicode characters in tweets, but that's also wrong. So perhaps 4111 is not where line 4328's `STDIN` gets the `:utf8` setting? Is `STDIN` there only used to receive commands and not actual user input?

4111 should be removed too, but I suspect that the binmode is being set for us by the locale. Maybe pull that line and throw a `binmode(C)` (yes, specifying no layer) after the `C` filehandle is opened (i.e., after the `close(P)`)?

**Comment by funnelfiasco** [comment]
Close, but not quite. Putting a bare `binmode` on `STDIN` on line 4111 seems to fix it so that utf8 errors go away but synch still works. I'm going to send it to the initial reporter and put it out on Twitter to get some testing. If nobody else finds regressions, I'll clean up the commits and merge it.
