### ISSUE TITLE
Issue with 'non default' list names using listson command...

### ISSUE THREAD

**Issue by kamiljk87** [oysttyer/oysttyer#124]
Looks like there is a problem proceeding private lists with non common schema like:
/liston $user/its_some_name which causing that error reply:
 *** list $user/its_some_name seems bogus; not added
the problem not occur when schema in use is:
/liston $user/listname
configuration:
oysttyer -dostream -ssl -vcheck -readline -verify -slowpost -notifytype=libnotify -notifies=dm,reply -notimeline
-- your version of Term::ReadLine::TTYtter is up to date (1.4)
-- your version of oysttyer is up to date (2.9.0)
os archlinux
/oysttyer-git 275.cf1d15d-1
/perl-term-readline-ttytter 1.4-3

**Comment by funnelfiasco** [comment]
I don't quite understand. What is the difference is between `$user/its_some_name` and `$user/listname`? Can you provide real example lists that trigger this behavior?

**Comment by kamiljk87** [comment]
i suppose, but that only mine guess it cant handling words separated with "_" between them in list name, bc not sure its name length issue. bc name exist already...

**Comment by kamiljk87** [comment]
aka itssomename vs its_some_name the seccond one schema causing issue and spawning error...

**Comment by funnelfiasco** [comment]
Ah okay, I understand now. I don't believe underscores are valid characters in list names. If you create a list with underscores in the name, they get converted to dashes for the purposes of API calls. 

For example, I just created a list named "this_is_a_list", which Twitter converted to https://twitter.com/FunnelFiasco/lists/this-is-a-list

If you replace your `_` with `-`, that should work. You can see all of your lists with the `/lists` command and it will show you the exact string to use. For example:

```
funnelfiasco> /lists <006
this_is_a_list (@FunnelFiasco/this-is-a-list) (f:0/0)
 "Isn't it?"
```

**Comment by kamiljk87** [comment]
Ha indeed thats interesting in web browser in past when was created its accepted that name with underscores w/o converting still appears, and can confirm its not throw error in schema $user/its-some-name and even looks like working, even with difference when web browser have "_" and console client show "-" in use... That mean kind of partially SOLVED with pointing at good idea in my opinion place on to_do_list: if possible on the fly rewrite used in /liston command "_" automatically to "-"... Thanks so much for support and helpful assistance in solving that..

**Comment by kamiljk87** [comment]
And funny thing is that /lists not show mine created list, but it show lists to which one im subscribed to (guess on fast look at them)... --edited-- or there is a limit showing items in that case would be nice also form ideas at end place info the list was stripped to eg. first xx positions....
