### ISSUE TITLE
credential check failed

### ISSUE THREAD

**Issue by isomorphisms** [oysttyer/oysttyer#125]
I just `git pull`ed the latest version, but I keep getting

```
** attempting to load extensions
** loading /opt/oysttyer-profile/profile.pl
-- using SSL for default URLs.
trying to find cURL ... /opt/curl
-- Streaming API enabled
-- checking oysttyer version: https://raw.githubusercontent.com/oysttyer/oysttyer/master/version_check.txt
-- warning: unable to verify oysttyer version
(checking credentials) FAILED. (13) bad password, login or URL? server down?
access failure on: https://api.twitter.com/1.1/statuses/home_timeline.json
to automatically wait for a connect, use -hold.
```

across many days. The password used to work so I don’t think that’s it.

**Comment by funnelfiasco** [comment]
There are two issues in your output:

1. Version check failure. GitHub had a [brief outage](https://twitter.com/githubstatus/status/892060343920414720) earlier this morning, which means oysttyer was not able to grab the version_check.txt file.

2. Credential failure. As for your credentials, top-of-tree is working for me. You may want to verify that you haven't de-authorized Oysttyer from your account. Did you create your own application key or are you using the built in default? If you didn't create your own, I suggest doing that (see [here](https://oysttyer.github.io/docs/userGuide.html#apikey) for instructions) as Twitter is prone to thinking our built-in key is spam.
