### ISSUE TITLE
Documentation of favourites/likes is outdated

### ISSUE THREAD

**Issue by gustafe** [oysttyer/oysttyer#128]
The page at

https://github.com/oysttyer/oysttyer/wiki/Built-in-commands 

lists `/f{ave|ourite}` etc as the command for faving/likeing a tweet.

The correct command is `/like` and variants.

I tried cloning the wiki to change directly but ran into an error.

Extract:

> /favourite [menu code] (/fave, /f), /unfavourite [menu code] (/unfave, /unf)
> 
> Favourites or unfavourites a tweet, respectively. See the section on tweet selection below.
> 
> /favourites (/faves, /fl) (+)
> 
> Displays your most recent favourite tweets. This command is synchronous and the foreground process will pause until the data is received or timed out.

**Comment by funnelfiasco** [comment]
Fixed in the wiki (I forgot atomicules even created that). Thanks for the reminder that I need to set aside a day or two and just write the dang documentation already. After the new year, I expect to have some time to actually put effort into this again.
