### ISSUE TITLE
.

### ISSUE THREAD

**Issue by tjharman** [oysttyer/oysttyer#129]

**Comment by tjharman** [comment]
I didn't actually mean to click submit on this, I was making a joke with a workmate.
Huge apologies.

**Comment by funnelfiasco** [comment]
Ha! This is hardly the worst issue ever opened on GitHub. 

I was wondering how quickly it would take someone to open an issue. We'll definitely bump the limit in the next release (I've given up on trying to guess when I'll get to it, so I'll just say it'll be out before the heat death of the universe) but in the meantime, you can adjust it yourself

**Comment by funnelfiasco** [comment]
...by setting the "linelength" setting.

**Comment by tjharman** [comment]
Oh gosh I'm sorry, I really didn't mean to be that guy.
Please just delete it fully!!!

**Comment by funnelfiasco** [comment]
GitHub doesn't support deleting issues, but I'm willing to pretend this doesn't exist. Sorry for reopening it earlier, I misclicked on my phone.
