### ISSUE TITLE
Readline regression

### ISSUE THREAD

**Issue by IvanSanchez** [oysttyer/oysttyer#13]
Somehow, readline is broken when upgrading from floodgap's to 2.2.2.

The old ttytter used to show this during startup:

```
-- readline using Term::ReadLine::TTYtter
```

But now:

```
-- readline using Term::ReadLine::Stub
```

**Comment by atomicules** [comment]
Any local Perl changes? Upgrading Perl version, etc? You might just need to re-install `Term::ReadLine::TTYtter`.

I'm not seeing this issue and haven't intentionally touched anything related to Readline. I've only ever had this issue when I've unintentionally upgraded Perl, etc.

**Comment by IvanSanchez** [comment]
Hm, this happened because I uninstalled the `ttytter` Debian package, which contains `Term::ReadLine::TTYtter`. My fault.
