### ISSUE TITLE
Enhancement: officially support 280 characters

### ISSUE THREAD

**Issue by gustafe** [oysttyer/oysttyer#130]
Now it seems we can all tweet twice as much -https://blog.twitter.com/official/en_us/topics/product/2017/tweetingmadeeasier.html

If possible, can tweets longer than 140 now be shown without the "... https://twitter.com/...." continuation? 

If this is a limitation of the Twitter API I guess nothing can be done.

**Comment by vitusson** [comment]
I have absolutely no problem that tweets by others longer than 140 wont be shown. What are you talking about?
The only thing is oysttyer wont let me send longer tweets. Which can be fixed by setting the 'lineleght' setting
https://github.com/oysttyer/oysttyer/issues/129

**Comment by gustafe** [comment]
Here's how a tweet is presented in Oysttyer now

![image](https://user-images.githubusercontent.com/8576740/32555758-eaee1d36-c49d-11e7-8623-1587719f27f6.png)

Here's the full text on Twitter's website 

![image](https://user-images.githubusercontent.com/8576740/32555778-f5fc7a2e-c49d-11e7-9828-ec271753940b.png)

I wonder if the content after "Down for..." can be shown. If desired this can be configurable.

**Comment by funnelfiasco** [comment]
Good news! There's already a setting for it: 
`extended=1`

This came about after Twitter made an API change a while ago. We left the shortened version as the default in case someone has an extension that can't handle > 140 characters. Now that the tweet length is increased across the board, it probably makes sense to update this default in the next release.

(Note that this is for display only. To enable sending more than 140 characters, you'll have to set the `linelength` value accordingly. This default will definitely change in the next release.)

**Comment by vitusson** [comment]
Well, I can see the whole tweet. Had this extended=1 set. That's why I asked what he meant.

**Comment by vitusson** [comment]
@funnelfiasco 
I set the linelength to 280 and can send long tweets now. I wondered if the $quotelinelength,  which is yet at 116, also need to be changed now?

**Comment by funnelfiasco** [comment]
@vitusson it doesn't look like the original reporter had this set, which is why I mentioned it. Yes, looks like `quotelinelength` will also need to be changed. I'll change it so that by default it's `linelength` minus `tco_length + 1` so that we're not making two changes the next time Twitter decides to change something.

**Comment by gustafe** [comment]
I’m moving over from `ttytter` and I’ve been trying to find differences in the docs, but unfortunately the documentation isn’t up to the previous standards...

**Comment by funnelfiasco** [comment]
That's a very polite way to say "the documentation is garbage". I've been meaning to take a day and fix that, but time has been very hard to come by lately. I really appreciate the community's patience.

**Comment by gustafe** [comment]
@funnelfiasco I'm fully aware from day job how hard it can be to keep docs up to date... if help is needed and I can provide I would like to.

**Comment by vitusson** [comment]
Updated docs would be great, especially the command-line option part, every time I want to look up something, like for linelength and extended today, I have to use the old http://www.floodgap.com/software/ttytter/copts.html and hope it's there.
Now I'd really like to offer a helping hand there, but since I don't know what some options do, I can't see how I could be helpful with that. Let us know if we can do something.

**Comment by funnelfiasco** [comment]
@gustafe @vitusson I started a User Guide a while back, so filling that in would be a good starting point. I'd be happy to accept pull requests to update the markdown source for it (https://github.com/oysttyer/oysttyer.github.io/blob/master/docs/userGuide.md) or even just opening issues against that repo for things that are missing. It's a little bit of a "there's too much to do so it's overwhelming and I don't do any of it" problem at the moment.

**Comment by vitusson** [comment]
@funnelfiasco Yep, discovered that one in the meantime, seems like a good place to start.
And maybe at last a good opportunity for me to learn how to work more with git, like what are "pull requests" and how do I make them . ;-)
All I ever did so so far was 'git clone' and 'git pull'... it's a shame

**Comment by funnelfiasco** [comment]
@vitusson Here's the GitHub docs for submitting pull requests: https://help.github.com/articles/creating-a-pull-request/
I'd also accept patches produced by `diff` or even just text dropped into an issue that I can copy/paste.

**Comment by vitusson** [comment]
Will read that. 
Now I see there is already a pull request by @slyall , who began adding a command-line section, that seems a good place to build on to and just add more things.  Is there a way I can get other peoples pull requests to my clone here on my pc and work on them?
