### ISSUE TITLE
Support 280 Characters ;)

### ISSUE THREAD

**Issue by NoiseEee** [oysttyer/oysttyer#131]
I figured I'd just be able to change a few numbers in the .pl script, but that's not the way this seems to work?

**Comment by NoiseEee** [comment]
Hi @funnelfiasco I actually just did a pull request... see the comments. Might be too 'heavy handed' but I'm using it at least :)

**Comment by vlbrown** [comment]
If there's something we can change locally, a patch we can apply between now and whenever the update is pushed, that would be swell.

**Comment by funnelfiasco** [comment]
You can set the `linelength` and `quotelinelength` settings to 280 and 256 respectively.

**Comment by jangliss** [comment]
Looks like this issue was resolved with https://github.com/oysttyer/oysttyer/commit/310da9c36f052e70e68eb00d019e7ca6d384c14f.

**Comment by debdrup** [comment]
Sorry for necroing this, but can a new release be cut, so that ports like [the freebsd one](https://www.freshports.org/net-im/oysttyer/) can be updated and benefit from 280 characters?

**Comment by funnelfiasco** [comment]
Yes. I won't promise a timeline, but soon. I also need to take a look at a few things related the death of the stream API. Fortunately, $dayjob is less overwhelming these days, so I really will be able to work on this soon.

**Comment by funnelfiasco** [comment]
I just announced an RC. I'll let it sit over the weekend and then push it out the door as 2.10.0 early next week.

https://github.com/oysttyer/oysttyer/blob/c020c1b28fd0fe200dfbde2d25e09a9cd4f874de/oysttyer.pl
