### ISSUE TITLE
User Streams API Deprecation August 2018

### ISSUE THREAD

**Issue by mackenzie-remote** [oysttyer/oysttyer#139]
Twitter [announced](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/user-stream.html) that they are retiring the user streams API

> Notice: We plan to sunset this API on Thursday August 16th, 2018. The Account Activity API will replace User Streams and Site Streams APIs. If you would like to migrate from the User Streams API to the Account Activity API, you should read through our [migration guide](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide).

They sent me an email telling me that my account was using the deprecated API. It looks to me like the `user.json` endpoint [is in the code as well](https://github.com/oysttyer/oysttyer/blob/master/oysttyer.pl#L732)

It's worth noting that Bitlbee have a [page on their Wiki](https://wiki.bitlbee.org/HowtoTwitter/StreamDeprecation) detailing how they are dealing with this.

**Comment by funnelfiasco** [comment]
It looks like Oysttyer will continue to work without the stream. It will basically be the behavior TTYtter had before the streaming API was introduced. I'd welcome work to incorporate the new API, but I don't have the bandwidth to do it myself.

**Comment by mackenzie-remote** [comment]
Thanks Ben, I was hoping that'd be the case.
