### ISSUE TITLE
Quoted tweets have empty geo coordinates (breaks geo extensions)

### ISSUE THREAD

**Issue by IvanSanchez** [oysttyer/oysttyer#14]
In floodgap's ttytter, `$tweet->{'geo'}->{'coordinates'}` used to be a two-dimensional array which contained latitude and longitude (or `undef`).

In 2.2.2, `$tweet->{'geo'}->{'coordinates'}` is an empty array.

This is making my [multigeo](https://github.com/IvanSanchez/ttytter-extensions/blob/master/multigeo.pl) extension to fail, and is making me sad.

**Comment by atomicules** [comment]
Ok, interesting! I've not intentionally done anything there, but will take a look. I too had noticed empty co-ordinates, but I'd never paid attention to them before so I just assumed I happened to be looking a tweets without them.

**Comment by IvanSanchez** [comment]
I suggest you give `multigeo.pl` a spin, and place a `Dumper($tweet->['geo'])` around line [583](https://github.com/IvanSanchez/ttytter-extensions/blob/master/multigeo.pl#L583).

Tweets might contain either coordinates, or a twitter place ID. Not a lot of people use coordinates nowadays, but maybe 1 tweet in every 50 in my stream does.

**Comment by atomicules** [comment]
As soon as I track down some geo-enabled tweets I'll debug this.

**Comment by IvanSanchez** [comment]
Hhhhmmmm, wait a second. I'm seeing tweets with coordinates (which are working OK), and I'm noticing that the errors come from the quoted tweets. Apparently all quoted tweets have empty coordinates.

**Comment by atomicules** [comment]
Ah, ok, well that could be something.

I just found a normal tweet in my stream (646008141306593280) that 
dumps the same in 2.1.0 and 2.2.2: no coords, but does have a place 
id.

But it is entirely possible I'm not doing whatever is needed for 
quoted tweets. I shall look into it.

Thanks.

**Comment by IvanSanchez** [comment]
Tweets with coordinates look like https://twitter.com/xurxosanz/status/646214917989761024

**Comment by atomicules** [comment]
I probably need to fix something in normalisejson, that's where I'd 
missed everything so far for quoted tweets.

**Comment by IvanSanchez** [comment]
Weird. For some reason TTYtter is using the string literal `'undef'` in place of the `undef` type for some tweets with coordinates. :-S

**Comment by atomicules** [comment]
Hi, just pushed a fix for this. I hope. I haven't tagged it as a 
release yet because I've just done the same undef stuff as 2.1.0 did 
and I get the impression that might not be quite correct?

**Comment by atomicules** [comment]
Same here. I think this fixes the issue, but re-open if it can be improved further
