### ISSUE TITLE
Adding a seperator in between bursts of updates?

### ISSUE THREAD

**Issue by werid** [oysttyer/oysttyer#141]
So, the past week or so, the user-streams have been on and off during the day, and I noticed, when following a lot of people, that the bursts of updates makes it hard to find my place again. 

Would it be possible to add a seperator inbetween these bursts of updates so i can easily find where the new tweets begin? 

If not in main code, maybe a plugin?

**Comment by classilla** [comment]
You can probably hook `$conclude` for that.

**Comment by funnelfiasco** [comment]
In 2.10, you'l be able to specify, e.g. `separator='###---#---#---#---###` to print that string between refreshes.
