### ISSUE TITLE
Allow `url` viewer to be stored in .oysttyerrc

### ISSUE THREAD

**Issue by sbaxter** [oysttyer/oysttyer#145]
I'd like oystterr to remember the value of `/set urlopen lynx -dump %U | more` between sessions.

If this is already a feature, could the docs be cleaned up with an example of how to accomplish this?

**Comment by vitusson** [comment]
That's already implemented.
Here I have 
urlopen=firefox --new-tab %U

And it's mentioned here https://github.com/oysttyer/oysttyer.github.io/blob/master/docs/userGuide.md#configuration
though not every single option is mentioned there, of course the syntax is the same for all
Though I don't know if it will work with your pipe, jut try it.

**Comment by sbaxter** [comment]
Aha: ```
/url menu code | Display the URLs in tweet menu code and open in the application defined by the urlopen option
```
-1 for attention to detail.
