### ISSUE TITLE
new tweet

### ISSUE THREAD

**Issue by ghost** [oysttyer/oysttyer#146]
Hi Dear,

I wanna create new tweet with your perl script. I cant find any command in the user guide page for new tweet.
Can you help me.

Cheers,

**Comment by funnelfiasco** [comment]
@Khamirak I apologize for the poor state of the documentation. If you're running interactively, you compose a new tweet by typing it and hitting enter. If you're just using it to send a tweet, it looks like

`oysttyer.pl --status='This is my tweet'`

You can also look at the [TTYtter documentation](http://www.floodgap.com/software/ttytter/) whenever something is missing and it will probably be correct.

**Comment by ghost** [comment]
thanks for your contribution.
