### ISSUE TITLE
Add a leading character to quoted tweets

### ISSUE THREAD

**Issue by IvanSanchez** [oysttyer/oysttyer#15]
Right now, retweets have a leading `%`, and replies have a leading `@`, prepended to the tweeter's username.

It would be nice if the default handler prepended a character (maybe `↑`?) to quoted tweets, in the same fashion.

**Comment by atomicules** [comment]
Well, I wasn't sure. For now the parent tweet has a " (quotation mark) 
prepended to the front, but the actual quote tweet has nothing.

I'm not sure which is best to mark up?

**Comment by IvanSanchez** [comment]
Personally I'd like the quoted one. Maybe there is a use case for prepending stuff to both the quoted and quoting tweets, so maybe the best thing is to add options for both (and leave one of them empty by default).

**Comment by atomicules** [comment]
I'll look into this, but will be a little trickier as I think I'll 
have to inject something into the tweet structure so I can target it 
here:

https://github.com/atomicules/TTYtter/blob/master/ttytter.pl#L5390-L5391

**Comment by atomicules** [comment]
Closing this out, but feel free to re-open if you feel it really should be possible to turn one or the other off
