### ISSUE TITLE
posting account

### ISSUE THREAD

**Issue by etamtlosz** [oysttyer/oysttyer#152]
My oysttyer is posting with my username/account and not with the "App Name" I've set up.
Is there a way to change this, or I did something wrong while setting it up?

**Comment by funnelfiasco** [comment]
@etamtlosz can you point me to a sample tweet? My tweets are posting with

`source                    <a href="https://github.com/oysttyer/oysttyer" rel="nofollow">OysTTYer (FunnelFiasco)</a>`

which is what I assume you're referring to.

**Comment by etamtlosz** [comment]
Test tweet -> https://twitter.com/loplo/status/1290385630375997440
Tweeted with using this command:
``
`./oysttyer.pl -status="This is an oysttyer test tweet"
-- using SSL for default URLs.
trying to find cURL ... /usr/bin/curl
test-login SUCCEEDED!
post attempt SUCCEEDED!
```
loplo is my twitter account, and according to my understanding, the oysttyer should post using the app name, in my case "Invercargill_weather". Am I right?

**Comment by funnelfiasco** [comment]
It is using your app name:

`source                    <a href="http://oysttyer.github.io" rel="nofollow">Invercargill_weather</a>`

(as opposed to, say, `<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>`)

What are you expecting?

The app name is the name of the app used to post the tweet, which is shown in some clients. If you want it to post as a different account, you need to use the Oauth tokens for that account.

**Comment by etamtlosz** [comment]
Thanks for making it clear. I was thinking it was going to use the app name as name.
