### ISSUE TITLE
Inserting newline doesn't work

### ISSUE THREAD

**Issue by edison23** [oysttyer/oysttyer#18]
Not sure if i'm doing something wrong, but when i have set `newline => 1` and try to tweet sth like `blabla \n this should be on a new line`, the tweet contains the `\n` string instead of an actual new line character.

**Comment by atomicules** [comment]
Hi.

-newline only affects display of received tweets, which could perhaps 
be clarified in the documentation.

As to how to send tweets from TTYtter, I'm really not sure. I'll have 
to look into this.

I thought there might be someway to insert something via Readline, but 
I've not figured it out yet. I've just now had a quick go modifying 
TTYtter to look for the "\n" characters and replace with an actual 
carriage return, but for whatever reason the carriage returns didn't 
actually make it through to Twitter.

**Comment by edison23** [comment]
I have tried to post a new line via --status option, but it didnt go thru either (i used actual new line character, not `\n` string), so now I've completely ran out of ideas how to post it.

**Comment by atomicules** [comment]
Just pushed a commit that allows sending of newlines. Any "\" followed 
by an "n" will be changed into a newline.

I don't to want tag this as a release just yet as there is one 
problem: It is no longer possible to send a literal "\" followed by an 
"n". Not sure what to do about this? Can't have it both ways. So 
perhaps this needs to be another option like -sendnewline?

**Comment by edison23** [comment]
wouldnt escaping it with another `\` be an option?

**Comment by tjharman** [comment]
Second what Edison said. That's the usual way these issues are handled, \ = \

**Comment by atomicules** [comment]
Ok, just pushed a commit that implements newline handling that way. If 
you have a "\n" it will get turned into a newline. If you have a "\n" 
it will be tweeted as a literal "\n". If you have a "\" it will 
become a "\".

There are still a couple of issues I need to sort I mention in the 
commit notes.
