### ISSUE TITLE
Can't use an undefined value as a HASH reference

### ISSUE THREAD

**Issue by atomicules** [oysttyer/oysttyer#2]
[Reported 2014-01-30](https://twitter.com/F3nr1s/statuses/428849405945339904)

References [line 5162](https://github.com/atomicules/TTYtter/blob/b3d254bee9a3ad0b74b8af16e5496cdbb8e271e7/ttytter.pl#L5162)

No sure what this one is on about. Not seeing it myself either.

**Comment by tjharman** [comment]
People are seeing this when they're not using SSL.

**Comment by atomicules** [comment]
Is that the only cause though? I wondered if it was fail whale related and therefore why only occasionally seen (I've never seen it).

**Comment by funnelfiasco** [comment]
This is pretty old. Since it's unconfirmed, I'm going to close it.
