### ISSUE TITLE
Replace newlines with spaces

### ISSUE THREAD

**Issue by IvanSanchez** [oysttyer/oysttyer#20]
Hi there,

Little feature request:

I've started using the `-newline` option to get rid of `\n` in my timeline. However, I personally find that using actual newlines in the output kinda breaks the flow of text.

I have noticed the code always replaces `\\n` with `\n` [around here](https://github.com/atomicules/TTYtter/blob/8ca7f0a2b7af50aa52964638ea48bc28c5b5dba7/ttytter.pl#L7585):

``` perl
    if ($newline) {
        $x =~ s/\\n/\n/sg;
        $x =~ s/\\r//sg;
    }
```

It would be great if there was a configurable way of replacing newlines with some other character or string, e.g. a space. Or a carriage return sign `␍`. Or a space-dash-space `-`. Or a paragraph sign `¶` `§`. Or whatever. This would allow me to keep the text compact, separate URLs with a newline just after them, and notice where the author intended to put a newline.

**Comment by atomicules** [comment]
I agree. I think. Lots of "\n" looks messy. Work on this might tie-in with #18, but it'll have to wait a bit as busy elsewhere at the moment.

**Comment by IvanSanchez** [comment]
Yeah, maybe the same character that a newline is replaced by should trigger a newline when writing. Not sure. I'll be using a temporary solution in the meantime using replacement UTF8 characters:

``` perl
use utf8;
```

``` perl
    if ($newline) {
        if ($seven) {
            $x =~ s/\\n/ [NL] /sg;
            $x =~ s/\\r/ [CR] /sg;
        } else {
            $x =~ s/\\n/ ␤ /sg;
            $x =~ s/\\r/ ␍ /sg;
        }
    }
```

Looks consistent IMHO (`␤` and `␍` are meant pretty much for this), but I don't have a (good) idea on how to compose tweets containing newlines.

**Comment by funnelfiasco** [comment]
Maybe `-newline` should change from a boolean to be a selected option? The user can decide to replace \n with a tab, a space, or a an actual newline. e.g.:

```
-newline=newline
-newline=tab
-newline=space
```

**Comment by atomicules** [comment]
Closing this out

With commits:
- 16ba40547bf1696c97d698b33f243e3bf8ce3399
- 53ff301291a123a855a68b195eb3f50a02009701
