### ISSUE TITLE
New name for TTYtter

### ISSUE THREAD

**Issue by atomicules** [oysttyer/oysttyer#24]
We've\* been given the provisional go-ahead from Cameron Kaiser for becoming the official fork and maintained replacement to TTYtter, but one of the conditions is adopting a new name.

Some ideas we have:
- TeaTeaTer
- TTYweet
- TTYeet
- sttytter
- SIGTTWEET
- TweeTerm

Please add any others you can think of as comments. We'll give it a week or so for ideas and then try to pick one we all agree on. And then I'll be able to change this from a personal repo to a community based one.

\* "We" as in anyone who is interested.

**Comment by edison23** [comment]
Personally, I like TweeTerm (could be also TwiTterm or something), because it's easy to pronounce (unlike TeaTeaTer, which is too long I think). SIGTWEET isn't bad either.

So, my idea is:
- twitterm (not sure about the capitalization, TwiTTerm, twitTerm, twitTERM, ... )
- CLItter (ehm, yea, that sounds like a dirty pun, I know)

**Comment by cwage** [comment]
I like twitterm, but it looks like that's already used for a few things -- an NPM module, etc.

**Comment by tjharman** [comment]
What about

twitty / twiTTY

It's like Twitter
It's still got tty in it.
It's short, sweet and pronounceable.

**Comment by atomicules** [comment]
Some others I thought of while cycling home:
- PerlsOfWisdom
- Perity (bit obscure: Perl + Parrots (bird,tweet) + "Who's a pretty boy then?")
- OysTTYer
- DontClamUp (bit naff)
- TeleTweet
- Twerminal
- TweeTTY (My current fav)

**Comment by tjharman** [comment]
I really like **TweeTTY**!

**Comment by atomicules** [comment]
@tjharman Oooh close, prefer TweeTTY though.

**Comment by tjharman** [comment]
Don't worry, so do I!

**Comment by atomicules** [comment]
Drat! taken!

http://sourceforge.net/projects/tweetty/

**Comment by IvanSanchez** [comment]
TweeTerm and Twetty are taken, so I'm gonna say +1 for Twerminal.

**Comment by jacoby** [comment]
"George". As in "I will hug it and squeeze it and call it George." (https://en.wikipedia.org/wiki/Of_Mice_and_Men_in_popular_culture#In_cartoons_and_animation)

**Comment by edison23** [comment]
I really like Twitty. The next best for me is Twerminal, but it's uncomfortably long, TBH.

**Comment by vehrka** [comment]
I'm also on a +1 for Twerminal

**Comment by atomicules** [comment]
Hmm, found this: https://github.com/developingo/twerminal

Naming things is hard.

**Comment by atomicules** [comment]
TwiTTYr? (There are lots of TwiTTY already).

Or go crazy: TTYTTYr

**Comment by atomicules** [comment]
Add in an extra "i" and we are probably ok with TwiiTTY.

But by now I'm kind of fed up with trying to play on TTYtter, TTY, Twitter and terminals, etc.

Maybe something different? Perlow as a contraction of Perls of Wisdom?

(I'm not at all concerned about finding a free twitter account username for the project either. We can just hashtag for support).

**Comment by atomicules** [comment]
Lots of "Chatty"s, but no ChaTTYer

Don't really like it though. Although almost beyond caring.

**Comment by atomicules** [comment]
naTTYr

For "Not another Twitter..." (From the Floodgap page). Also has TTY. And also pronounced as "Natter" which means to chat, etc.

**Comment by funnelfiasco** [comment]
It's been 8 days, I think it's time to put it to a vote: Here's a form ballot, select as many as you like. https://docs.google.com/forms/d/1xkufmfy6WkeEDKRpuflIzCaKE-LKVBYw3GTt3zl_iAI/viewform?usp=send_form

(I dropped any proposals that had name collisions with other Twitter clients or any that could be misread as inappropriate names)

**Comment by atomicules** [comment]
@funnelfiasco Any clear winner yet?

**Comment by funnelfiasco** [comment]
As of today, it looks like twitterm is the clear winner. Full voting results:

```
9 twitterm
5 twiTTY
3 TTYweet
3 TTYeet
3 TTYTTYr
3 SIGTTWEET
3 OysTTYer
2 TweeTTY
2 Perity
1 sttytter
1 PerlsOfWisdom
0 TwiTTYr
0 DontClamUp
```

**Comment by atomicules** [comment]
Hmm, there are a couple of "twitterm"s on Github and some "twitty"s as 
well. 

Which gets us to no clear winner.

I'm stuck as to what to do.

**Comment by funnelfiasco** [comment]
Hm, I'm not sure how I missed that when checking for collisions (or I didn't but accidentally re-added it in the survey). I say you just declare a winner among your favorites (I'm partial to OysTTYer).

**Comment by atomicules** [comment]
Ok, I'll pick one of the 3 vote ones tomorrow (or at the weekend) and 
start transitioning to an organisation, etc.

**Comment by atomicules** [comment]
Ok, by unpopular vote we've gone with oysttyer. I really don't mind it either. It's got "TTY" in it and there is the link to Perl as well.
