### ISSUE TITLE
Switch everything over to new name - oysttyer

### ISSUE THREAD

**Issue by atomicules** [oysttyer/oysttyer#27]
Working on this this weekend.
- [X] Register Twitter account
- [X] Get new API key 
- [x] Switch source code over s/ttytter/oysttyer , etc.

**Comment by IvanSanchez** [comment]
We need a logo. An oyster shell with an `@` instead of a pearl or something.

**Comment by atomicules** [comment]
Great idea! Thanks for volunteering ;-)

**Comment by IvanSanchez** [comment]
```
/⎺\
>@<
⎺⎺⎺

/⎺\
>@<
⎺⏡⎺

/⎺\
>@<
\_/



```

**Comment by edison23** [comment]
ok, how about something like this? pearl in an oyster.. i know it's a bit more complex, but the "splash screen" already has something more or less this complex, right?

```
      .~####~.                 
      # ., .#`                 
    .|`,. /#`                  
    ([.~ #/                    
    `|$./ .~########~.         
     #~.@*     ` `´.  *@.      
     (/.   ,@@.     ˇ.  `@     
     `\`.  `@@´       .  @     
      `*..      .....` _#      
        `^~#########~**        
             `~#~´             

 _      _             _        
/ \ | ||_  |_ |_ | | /_\|´`    
\_/ \_| _|´|_´|_ \_| \_ |      
      |            |           
```

**Comment by atomicules** [comment]
Wow, impressive.

**Comment by IvanSanchez** [comment]
```
  _
 / /
 |/___
 < @  )
  ----
```

**Comment by atomicules** [comment]
I'm up for using both of these. The big one as the splash screen and 
the smaller one for the Twitter avatar, etc.

**Comment by edison23** [comment]
ok, i'll try to improve mine to make it look better, this was a fast sketch.. you can choose then from the two versions

**Comment by edison23** [comment]
ok, so i figured one `@` will be better than four as a pearl, but I'm not 100 % positive on that being a good move, so I can reverse it, if you guys dont like it. I also avoided using `@` anywhere else, plus I added dot into the center of the `O`... just bcs I like it, reminds me of the pearl in the center of the oyster.

```
          ¸                       
       .#*^#=.                 
      %´., .#`                 
    ¸/´,  /#`                  
    ({.  #/                    
    `\&¸/.-~=#######=.,        
      #%´*     ¯ `´.  *\.      
     (%.            ˋ.  `&     
     `&`    @    ` .  .  #     
      `\`¸¸¸    .....ˊ ¸%´       
        `^~#########=~*´       
             `~=~´             

   _      _             _      
  /.\ | ||_  |_ |_ | | /_\|´`  
  \_/ \_| _|´|_´|_ \_| \_ |    
        |            |         
```

**Comment by atomicules** [comment]
@edison23 I've had to tweak some of the characters (as in slightly ruin your artistic talent) a bit as I was having trouble getting them to display properly. Might just have been my font/terminal combination, etc. Once I get everything changed over, tested and push up here you'll be able to take a look and see if you can get it back to how you had it.

**Comment by edison23** [comment]
no problem, i probably shouldnt have used those french accents, that's true.. 

a/w it occured to me now, that it might look to someone like a toiler.. i should try to fix that xD

**Comment by IvanSanchez** [comment]
I think I can fiddle with a few variations. At least this doesn't look like a toilet much :-P

```
  __
 / /
 |/___
 < @  )
  `---
```

**Comment by edison23** [comment]
@atomicules ok, how about this? I tried to remove all the obscure characters and fiddled w/ it to make it look less like a toilet.

``````
      .#*^#=.                 
      %´.,`.#`                 
    ;´,. ./#`                  
   ({.`,` #/                    
   `& ,` %,~=*'"*=~=-.,        
    \`=_/´.``  -  `´.  *\.      
     (%.  -  -      ˋ-. `&     
     `&`  ~     @      . #     
      `\`. `    .....ˊ  %´       
        `^~._.,,,.-+=~*´       
             ````´´´             

   _      _             _      
  /.\ | ||_  |_ |_ | | /_\|´`  
  \_/ \_| _|´|_´|_ \_| \_ |    
        |            |         
``````

**Comment by atomicules** [comment]
For whatever reason, it is the ´ character which causes problems. 
Would be interesting for others to test using that character as well. 
For the time being I've changed to '

**Comment by funnelfiasco** [comment]
Related question: do we want to support the .ttytter(rc|key) file names for a while or just make a clean cutover?

**Comment by atomicules** [comment]
I've gone for clean cut-over. Would need new key anyway as had to register a new api key.

**Comment by funnelfiasco** [comment]
Looks like this is all done as of the 2.5.0 release.
