### ISSUE TITLE
Organisation members

### ISSUE THREAD

**Issue by atomicules** [oysttyer/oysttyer#29]
I've given @funnelfiasco and @IvanSanchez owner access as I've had most communication with them and so "trust" them, so to speak. They will be free to set others as owners of course. This shouldn't just be owned by me.

And then I'm trying to add as members those who have shown interest or written plugins for TTYtter in the past. So far @edison23 @tjharman @colindean @pr4wn.

**Comment by atomicules** [comment]
Added @vkoser and @reuteras since mentioned on Floodgap as writing extensions.

**Comment by atomicules** [comment]
Oh, also @stormdragon2976 for the same reason.

**Comment by atomicules** [comment]
Added @vehrka based on @IvanSanchez [tweet](https://twitter.com/RealIvanSanchez/status/667632756495679488) earlier.

**Comment by atomicules** [comment]
Done for now, I think?

**Comment by stormdragon2976** [comment]
This is great, TTYTTer was the best part of Twitter lol. I hope that a lot of work will go into this project to make it gnu social compatable. While we may need to worry about Twitter changing their API again for the purpose of chasing away third party developers, GNU Social would not do such a thing.

**Comment by colindean** [comment]
While I certainly appreciate the consideration, I don't think I have anything to contribute further. I've not actively used TTYtter for a few years, as I now actively manage eight Twitter accounts with Tweetdeck.

Good luck! TTYtter was my go-to for a lot of years when keeping things in a terminal was the only way to maintain productivity while tweeting ;-)

**Comment by atomicules** [comment]
Hi @colindean no problem. I just didn't want to exclude anyone who may have been interested.

**Comment by colindean** [comment]
No worries at all. 🍻

**Comment by atomicules** [comment]
@stormdragon2976 I've not intentionally broken any existing non-twitter support, but I haven't checked if it currently works with Gnu Social. If we can support both Twitter and Gnu Social that would be great.

**Comment by reuteras** [comment]
Like @colindean I haven't actively used TTYtter for years. I wish you good luck and I might check out this client over the holidays since it's always fun to have a terminal alternative :)

**Comment by chrisvoncsefalvay** [comment]
I am actively using oysttyer (I wish I could remember how to type it every time :S) after using ttytter for yeeeeears. I'm thinking of spending some time picking up some issues. Happy to be added.

**Comment by atomicules** [comment]
@chrisvoncsefalvay Sent an invite so you can be a member. Sorry for the delay, but I'm not often on the Github website itself.

**Comment by atomicules** [comment]
Closing this out. If anyone wants to join in the future then you know who to ask.

**Comment by atomicules** [comment]
Should somewhat officially mention it somewhere (although it's been obvious from lack of activity here), but for whatever reason I've just found myself using Twitter less and less over the past year and coupled with other things I've just kind of drifted away from this project; I've always been better at working on projects I actively use and since I'm not even using Twitter... well.

Probably not a permanent thing and seems in _very_ good hands with @funnelfiasco (thanks!).

Will be back at some point.

**Comment by stormdragon2976** [comment]
Interestingly, Oysttyer works pretty well with GNU Social. I no longer use Twitter at all. I haven't in well over a year. However, I do use Oysttyer all the time. It gives sound notifications for new events for me, using my soundpack extension. What I would really love, is for Oysttyer to be shifted to support open projects like GNU Social and Mastodon with Twitter support as an after thought. It's just a matter of time before they alienate the rest of their user base anyway. I'm not all that great at perl, but I'm willing to help as much as I can to make this transformation take place if everyone else is on board with it. I don't think it would take all that much, and we could even us the Oauth support provided by GNU Social as an option, and I believe it's mandatory for mastodon.

**Comment by funnelfiasco** [comment]
Thanks for all your hard work, @atomicules, looking forward to having you back at some point.

**Comment by IvanSanchez** [comment]
@atomicules I know the feeling of not having time for all the projects.

@stormdragon2976 This should be a good moment to point out that, albeit I've been away from Oysttyer for a time myself, I have done some work on a multi-platform multi-account twitter+mastodon client: https://gitlab.com/IvanSanchez/soclial . It's quite buggy, but the code is not a spaghetti mess, plus using a priority queue and JS promises makes asynchronicity a bliss.

**Comment by stormdragon2976** [comment]
Nice client. I also have one called gasher, written completely in bash. it isn't like Oysttyer, but it does have quite a bit of functionality. I use GNU Social mostly, so it does not yet have mastodon support, but I may try to add it some day, unless someone else beats me to it.
