### ISSUE TITLE
Add support for multiple images

### ISSUE THREAD

**Issue by atomicules** [oysttyer/oysttyer#3]
Maybe.

As per [Twitters announcement](https://blog.twitter.com/2014/photos-just-got-more-social) that it's now possible to include up to four images with a tweet. 

I can't find any mention of this in the API documentation though.

**Comment by atomicules** [comment]
See this gist: https://gist.github.com/myshkin/5bfb2f5e795bc2cf2146

**Comment by tjharman** [comment]
How to apply that gist?

I get the following:

root@animal:/usr/bin# patch < tit.diff
patching file ttytter
Hunk #1 FAILED at 2837.
Hunk #2 FAILED at 5333.
Hunk #3 FAILED at 5351.
Hunk #4 FAILED at 7027.
4 out of 4 hunks FAILED -- saving rejects to file ttytter.rej

**Comment by atomicules** [comment]
@tjharman I'm not sure. I posted that link for information and future reference for working on this issue. I've not tried it myself. Perhaps the diff is against a slightly different version that the one you are trying to patch? Might be worth asking [justarobert on Twitter](https://twitter.com/justarobert/statuses/587344250028691456)
