### ISSUE TITLE
Community infrastructure

### ISSUE THREAD

**Issue by funnelfiasco** [oysttyer/oysttyer#30]
Do we want mailing lists, IRC channels, a website, etc?

**Comment by funnelfiasco** [comment]
I've created and registered #oysttyer on Freenode. Msg bcotton for op.

**Comment by atomicules** [comment]
Probably only want as much as we are willing to manage. Could just use github pages as the website and not bother with a domain name, etc.

**Comment by atomicules** [comment]
Also see #29

**Comment by funnelfiasco** [comment]
I certainly don't mind paying for a domain and running mailman and some simple HTML, but if nobody else will use it, I won't bother.

**Comment by edison23** [comment]
@funnelfiasco couldnt the channel be on Rizon? I think many more people dwell there (including me) and thus are more likely to come

**Comment by edison23** [comment]
Ad web: I think my friend could provide a VPS where we could run the web if we wanted

**Comment by funnelfiasco** [comment]
@edison23 it certainly could. Freenode seems to be the place where most FLOSS projects live (though the Floodgap license makes oysttyer not technically a FLOSS project). I'm not particularly wedded to it, though.

**Comment by edison23** [comment]
@funnelfiasco Then I would start the channel at Rizon rather than at Freenode if you and others don't mind... should I register one, or shall we leave that to da boss? ;)

**Comment by funnelfiasco** [comment]
Sorry, didn't mean to leave you hanging so long. I still think Freenode is a more "appropriate" place, but I also don't particularly care. If you want to start a channel at Rizon, go ahead. I'll /topic the Freenode channel to point to that one.

**Comment by edison23** [comment]
NP, I realized don't have a problem with the channel on Freenode, I was just being lazy getting used to another network xD

Question remains, what about the website?

**Comment by IvanSanchez** [comment]
> what about the website?

First, we need some 90s-style animated GIFs of clams and oysters.....

**Comment by funnelfiasco** [comment]
We can use GitHub pages for the website (and in fact we do, though I still need to work on the docs) and there's nothing else outstanding, so I'm going to close this issue.
