### ISSUE TITLE
"Application cannot perform write operations"

### ISSUE THREAD

**Issue by IvanSanchez** [oysttyer/oysttyer#32]
So I try to RT something this morning and the following error message pops up:

```
*** warning: server error message received                                                   
*** "Application cannot perform write actions. Contact Twitter Platform Operations through https://support.twitter.com/forms/platform"
```

Has there been any problem with the oysttyer API key?

**Comment by atomicules** [comment]
Nothing I know about. Will check this out.

**Comment by edison23** [comment]
I am experiencing this as well, also from today's morning

**Comment by atomicules** [comment]
Looks like it is Twitter being their usual kind selves to developers. 
It's been intentionally suspended, supposedly for breaching terms of 
the API, which we haven't done because no significant changes have 
been made since TTYtter; the only potential thing is we still say fav 
instead of like, but I just haven't had time to change that yet.

No email from them like they are supposed to do. 

I'll have to log a support ticket. Will update here when I have more 
info.

**Comment by atomicules** [comment]
This might take a few days to sort out.

**Comment by IvanSanchez** [comment]
Manually changing the values of the oauthkey and secret might help (circa line 970).

Perhaps twitter looks for oauth secrets in github and automatically bans ones available in plain-text? Maybe it's time to use something super-secret like ROT13.

**Comment by atomicules** [comment]
Maybe, seems odd that all the time I had TTYtter mirrored they never 
blocked that though.

Bad timing for this today, I'm off work, but really busy at home. 
Would have been easier to sort out if I'd been at work.

**Comment by atomicules** [comment]
Logged support ticket, got automated email, sent follow-up to that. 
Need to know what our non-compliance is so hoping a human being 
somewhere will read the ticket.

**Comment by IvanSanchez** [comment]
I've just read https://twitter.com/oysttyer/statuses/671966507971289088, does that mean we can close this issue?

**Comment by atomicules** [comment]
Right, we are back working. So thanks to Twitter as they were actually pretty quick. I _think_, based on their reply (see below), that we tripped an automated spam block, probably due to the flourish of tweets when oysttyer launched.

> Hello @oysttyer, Thank you for reaching out. We have reviewed your request and have reactivated your API key. To avoid being caught by automated spam filters you must send a variety of Tweets that do not always include @handles, the same/similar URLs, and/or hashtags. Going forward, carefully ensure that your application adheres to Twitter’s policies: Developer Agreement and Policy Automation Rules Best Practices Developer Display Requirements Twitter Rules Please note, applications found to be violating policy again are subject to permanent suspension.  Regards, Twitter Platform Operations

**Comment by atomicules** [comment]
@IvanSanchez Yes, closing out.

**Comment by funnelfiasco** [comment]
Looks like we're blocked again. I just got this message.

**Comment by greenled** [comment]
Me too. Got the same problem.

**Comment by atomicules** [comment]
Drat. I've not seen anything from Twitter, so the likelihood is we've 
just tripped an automatic spam prevention thing again. I'll raise a 
ticket with them again and let you all know when I've had a response.

**Comment by atomicules** [comment]
Hi. We are back in working order. Twitter sent this advice, but I'm 
not sure there is much we can do about it apart from suggest Oysttyer 
users never mention Oysttyer ever?

> Hello, Yes you were muzzled for the same reason as before. We have 
> reactivated your app. Please do remind your users, however, that to 
> avoid being caught by automated spam filters they must send a 
> variety of Tweets that do not always include @handles, the 
> same/similar URLs, and/or hashtags.
> 
> If not your app will continued to be restricted. 
> 
> Regards,Twitter 
> Platform Operations

**Comment by funnelfiasco** [comment]
IDK if it's even a matter of mentioning Oysttyer. It reads to me like people who use the API key (which is all users) can trigger it. In which case, how did TTYtter ever manage? Sounds like Twitter is being awful. Can you try to push them on this a little bit?

**Comment by IvanSanchez** [comment]
Argh, this is happening **again**.

(╯°□°)╯︵ ┻━┻

**Comment by funnelfiasco** [comment]
I believe TTYtter arranged a special exception that kept that flag from getting thrown. Perhaps @Classilla can provide some guidance?

**Comment by atomicules** [comment]
I'll raise a ticket again. Thanks for reporting it here, been off 
Twitter altogether today as just been insanely busy.

I'll do as suggested last time and see if we can get a permanent fix 
from Twitter.

Will let you all know when we can tweet again.

**Comment by classilla** [comment]
> I believe TTYtter arranged a special exception that kept that flag from getting thrown. Perhaps @Classilla can provide some guidance?

I probably did have some special dispensation, but it wasn't a formal arrangement, so I can't really advise you. That was during the days of Taylor Singletary and I guess it carried over.

**Comment by atomicules** [comment]
I've not heard anything back from Twitter since Friday, but it was 
late evening UK time and then it has been the weekend. Hopefully the 
longer response time this time round means they are considering a more 
permanent resolution. In the meantime I've merged in the changes that 
allow you to specify your own oauthkey and oauthsecret.

**Comment by atomicules** [comment]
Hi all, I've received a reply from Twitter and we are unmuzzled again, 
but this is the last chance they are giving us:

> Hello oysttyer organisation, Thanks for the follow up. We can confirm that you app is not being restricted for a rate limit error. Per our previous emails this is caused by the users of your app far too frequently posting Tweets containing handles, hashtags and/or URLs. This is viewed as spam. We have reactivated your app, but this is the final time that we will so for this behavior. Regards,Twitter Platform Operations 

I have asked for more clarification and details on whether we have 
accidentally triggered the spam block via real users or whether 
someone has stolen our keys. If it is a key stealing issue then 
perhaps just some form of obfuscation would do the trick (It'd stop 
scrapers, etc).

We will see how we go. If all else fails we can make supplying your 
own oauthkey and secret the default. It is a little bit harder to 
set-up, but not really that much hassle for oysttyer's target users.

**Comment by funnelfiasco** [comment]
I vote we go ahead with the "bring your own oauthkey" plan. Twitter seems to be completely uninterested in working with us on this.

**Comment by atomicules** [comment]
On 22-Dec-2015 14:42:03, Ben Cotton wrote:

> I vote we go ahead with the "bring your own oauthkey" plan. 

Yeah, it isn't actually a bad idea. I wonder if we can streamline it 
at all during set-up, or perhaps it just needs clearer docs?

**Comment by funnelfiasco** [comment]
I think better docs are probably sufficient. I was able to figure it out pretty quickly while only halfway knowing what I was doing. See my recent comment on #28 about docs. I should be able to get at least basic user docs done in the next few days.

**Comment by atomicules** [comment]
Just had a look at TwitVim and we aren't the only application to store 
the consumer key and secret in plain sight so I don't think that is 
the issue necessarily.

It is either that Twitter wants to kill us off (but in all fairness 
they have been pretty co-operative in re-activating us) or perhaps 
there are spammers out there utilising oysttyer.

In which case, obfuscation would never help us, but supplying your own 
keys would.

**Comment by greenled** [comment]
> Hi all, I've received a reply from Twitter and we are unmuzzled again,
> but this is the last chance they are giving us:
> 
> > Hello oysttyer organisation, Thanks for the follow up. We can confirm
> > that you app is not being restricted for a rate limit error. Per our
> > previous emails this is caused by the users of your app far too
> > frequently posting Tweets containing handles, hashtags and/or URLs. This
> > is viewed as spam. We have reactivated your app, but this is the final
> > time that we will so for this behavior. Regards,Twitter Platform
> > Operations
> 
> I have asked for more clarification and details on whether we have
> accidentally triggered the spam block via real users or whether
> someone has stolen our keys. If it is a key stealing issue then
> perhaps just some form of obfuscation would do the trick (It'd stop
> scrapers, etc).
> 
> We will see how we go. If all else fails we can make supplying your
> own oauthkey and secret the default. It is a little bit harder to
> set-up, but not really that much hassle for oysttyer's target users.

I think it's a good idea. That way spammers won't bother us again.

**Comment by atomicules** [comment]
Heard back from Twitter again on this regarding what is triggering the spam 
block:

> Hello oysttyer organisation, Thanks for the follow up. It is the 
> repeated use of handles, hashtags, etc. that is viewed as spamming 
> behavior. The specific handles, hashtags, etc. do not matter here.  
> Regenerating your consumer key will not lift any future API 
> restrictions. If your app is again restricted please write back into 
> this help desk. 

So we still don't know exactly what hashtags or handles were causing it. 
I can still only presume it was the mentions of Oysttyer itself.

I think we've done what we can. If we do get restricted again (which 
will be permanent) then users will just have to switch to their own 
consumer keys.

**Comment by leokhachatorians** [comment]
Well, from my knowledge of messing around twitters API, there really isn't anyway to prevent this. The spam filter is highly sensitive to any series of tweets with a mention, it isn't associated with a particular mention from what I've seen.

In my experience with my toy apps, having anywhere from 10 to 30 consecutive tweets with a mention included in the body is subject for the read/write access to be suspended. It sucks :(

**Comment by atomicules** [comment]
Closing out. If we ever get blocked again the solution is to use your own keys.

**Comment by Tapudp** [comment]
I'm facing the same, is it because they might have banned my bot or something?

**Comment by funnelfiasco** [comment]
@Tapudp it could be. If you're using the built-in key, don't. If you're using a key you generated, you'll have to contact Twitter support for more information.

**Comment by Tapudp** [comment]
Yeah I'm using my own generated key, and it is simply a twitter App that I have created with all those consumer key, tokens and all, my exact error is following does that mean I have some mistakes on my side 

```
'Application cannot perform write actions. Contact Twitter Platform Operations through https://support.twitter.com/forms/platform',
    code: 261
```

**Comment by knightjoe2222** [comment]
@Tapudp did you ever get this sorted?
