### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by kiwiG** [oysttyer/oysttyer#33]
Running a new installation, when hitting Enter after the Welcome text I get:

Request from https://api.twitter.com/oauth/request_token ...... FAILED!: ""
unable to fetch token. here are some possible reasons:
- root certificates are not updated (see documentation)
- you entered your authentication information wrong
- your computer's clock is not set correctly
- Twitter farted
  fix these possible problems, or try again later.

My clock's OK. What can I do about the other possibilities?

**Comment by tjharman** [comment]
What message do you get if you type

curl https://api.twitter.com/oauth/request_token

on the cli?

**Comment by kiwiG** [comment]
curl: (6) Could not resolve host: api.twitter.com

**Comment by tjharman** [comment]
Well, there's your problem.
Why can't your curl find api.twitter.com

Is your DNS set correctly etc?

This isn't a oysttyer issue, this is a network/dns issue local to you.

**Comment by kiwiG** [comment]
Yeah, you're right. Just tried a ping. The server's down. D-oh! Excuse my brain fart!
