### ISSUE TITLE
Do not display own name on sent DMs

### ISSUE THREAD

**Issue by IvanSanchez** [oysttyer/oysttyer#37]
Right now, when a DM is sent to another person, it goes like this:

```
oysttyer> /dm somebodyelse Foobar
[DM da2][RealIvanSanchez/2015-12-04 13:55:39] Foobar
```

So it's pretty hard to see who I just sent the DM to. Instead, this would be preferred:

```
[DM da2][→somebodyelse/2015-12-04 13:55:39] Foobar
```

Or even

```
[DM da2][RealIvanSanchez→somebodyelse/2015-12-04 13:55:39] Foobar
```

Or something like that.

**Comment by atomicules** [comment]
@ivansanchez I just had a look into this and I'm not seeing this issue. I.e. if I send a dm it gets formatted as:

```
[DM da0][->anotheruser/Wed Mar 09 17:29:27 +0000 2016] Testing dms
```

And this mark-up/formatting has been there since TTYtter (line 5621):

```
$sns = "->" . &descape($ref->{'recipient'}->{'screen_name'});
```

Same mark-up applies for `/dmsent`.

**Comment by IvanSanchez** [comment]
The problem is in [oysttyer.pl#L1371](https://github.com/oysttyer/oysttyer/blob/master/oysttyer.pl#L1371): the `$whoami` variable is lowercased.

So when the comparison for the DM sender is done around 5620, your oysttyer is comparing `atomicules` vs `atomicules` but my oysttyer is comparing `realivansanchez` vs `RealIvanSanchez`.

**Comment by atomicules** [comment]
Excellent info, thanks!
