### ISSUE TITLE
Allow quoted tweets to be appended after original tweet

### ISSUE THREAD

**Issue by mackenzie-remote** [oysttyer/oysttyer#38]
This is a feature request. Could there be an option to allow quoted tweets to be appended after the original tweet?

Before:

```
e3> [21:10] <(listname)"%tweeter1> Original tweet. https://twitter.com/tweeter2/status/123456789012345678
e4> [20:53] (x2) <↑tweeter2> Quoted tweet
```

After:

```
e3> [21:10] <(listname)"%tweeter1> Original tweet. [<↑tweeter2> Quoted tweet]
```

**Comment by atomicules** [comment]
Hi,

Last time I checked, it's API rules that we have to keep the `https://twitter.com/tweeter2/status/123456789012345678` bit. Only the official Twitter client gets to remove that it seems.

So I think it'd be too messy visually to have all of it one one line. But I'm open for discussion.

**Comment by mackenzie-remote** [comment]
I'd still be happy with this if it's possible.

```
e3> [21:10] <(listname)"%tweeter1> Original tweet. https://twitter.com/tweeter2/status/123456789012345678 [<↑tweeter2> Quoted tweet]
```

**Comment by atomicules** [comment]
The other problem with doing this is it wouldn't be possible to do anything to the quoted tweet as it wouldn't have a menu code. It would limit functionality a bit.

**Comment by mackenzie-remote** [comment]
Fair enough, it sounds as if it's not really feasible. Thanks for all your work on this project.

**Comment by edison23** [comment]
honestly, I'm against this idea, it seems to me that it'd be messy and I very much like it as it is now..  just sharing my opinion

**Comment by atomicules** [comment]
For reference, this is the post clarifying we have to keep the url of the quoted tweet:

https://twittercommunity.com/t/api-returns-url-to-twitters-status-update-at-the-end-of-the-text/50424/5

**Comment by atomicules** [comment]
@kenzeh You didn't have to close it straight away. I'm fine for a bit of a discussion around things. When I first started trying to implement quoted statuses I too wanted it displayed like you suggested because that's how TTYtter worked things internally to display retweets. But the more I thought about it, it was easier to append the quoted tweet because of the issue around menu codes, etc. However, that's just me and my Perl skills at that moment in time, perhaps someone (or me) can figure out away to do this better one day.

**Comment by IvanSanchez** [comment]
I guess that it _might_ be possible to do this with a `handler` extension.

**Comment by mackenzie-remote** [comment]
@atomicules No worries, just didn't want to leave your issues full of unfixable things. If it's fixable I'd be grateful for the feature!
