### ISSUE TITLE
/mute and /unmute @user

### ISSUE THREAD

**Issue by hak4fun** [oysttyer/oysttyer#40]
SUGGESTION: 
the code below woks fine for me. Maybe not a big deal for you to build in next revision

``` perl
$muteurl ||= "${apibase}/mutes/users/create.json";
$unmuteurl ||= "${apibase}/mutes/users/destroy.json";
...
...
    if (m#^/(mute|unmute) \@?([^\s/]+)$#) {
        my $m = $1;
        my $u = lc($2);
        if ($m eq 'mute') { 
            $answer = lc(&linein(
    "-- sure you want to mute $u? (only y or Y is affirmative):"));
            if ($answer ne 'y') {
                print $stdout "-- ok, $u is NOT muted.\n";
                return 0;
            }
        }
        &muteuser($u, 1,
            (($m eq 'mute') ? $muteurl : $unmuteurl),
            (($m eq 'mute') ? 'started' : 'stopped'));
        return 0;
    }

...
...
...


sub muteuser {
    my $uname = shift;
    my $interactive = shift;
    my $basef = shift;
    my $verb = shift;

    my ($en, $em) = &central_cd_dispatch("screen_name=$uname",
        $interactive, $basef);
    print $stdout "-- ok, you have $verb muted user $uname.\n"
        if ($interactive && !$en);
    return 0;
}

...
...
...
...
```

**Comment by IvanSanchez** [comment]
Maybe you can publish this as an extension, with `$addaction`? I recall `/report` was implemented first as an extension, at https://github.com/reuteras/my-ttytter-addons

**Comment by IvanSanchez** [comment]
Otherwise, if you've already got the code into the main oysttyer file, send a pull request instead - it makes testing and merging the code **so** much easier.

**Comment by hak4fun** [comment]
i try to "pull'a'request" or whatever....

**Comment by IvanSanchez** [comment]
@hak4fun Read https://help.github.com/articles/fork-a-repo/ and https://help.github.com/articles/using-pull-requests/ before you set fire to something :-P

**Comment by hak4fun** [comment]
Hope you will build it in ....it's so simple same like /block /unblock functions....

**Comment by atomicules** [comment]
Thanks very much for this contribution and apologies it took so long to merge it in.
