### ISSUE TITLE
ID's of DM in script mode

### ISSUE THREAD

**Issue by hak4fun** [oysttyer/oysttyer#41]
BUG?

I'm checking all the DM's with below command from script.

~./TTYtter.pl -runcommand="/dmagain +30" -verbose -keyf=key.txt -rc=rc.txt > out.txt

Thought -runcommand implies -script option, but i don't see DM IDs in the output but display codes. So I can't delete the spam DM's automatically.

out.txt:
[DM db5][Mummy/Fri Jul 03 12:21:08 +0000 2015]  bla bla bla...
[DM db6][Barack_Obama/Fri Jul 03 12:21:13 +0000 2015] yes we can... 

also the timestamp is not good to handle....

better like this:
2015.12.09 16:31:55 {dm,555555555555555555} @Barack_Obama yes we can...

**Comment by atomicules** [comment]
Sorry for the long delay in looking at this, but I pushed it out to tie in with the dm milestone. Now I've started looking at this issue it doesn't actually require changes to Oysttyer and this can be solved with existing functionality (extensions).

What you can do is define an extension called `dmids.pl` and within it put this code:

```
$dmhandle = sub {
    my $ref = shift;
    my ($time, $ts) = &wraptime($ref->{'created_at'});
    print $streamout (
        $ts, " {dm,",
        $ref->{'id_str'}, "} <@",
        &descape($ref->{'sender'}->{'screen_name'}), "> ",
        &descape($ref->{'text'}), "\n");
    return 1;
};
```

And then on the command line run:

```
perl /path/to/oysttyer.pl -runcommand="/dmagain +30" -keyf=key.txt -rc=rc.txt -exts=/path/to/dmids.pl -timestamp="%Y.%m.%d %H:%M:%S" > out.txt
```

I do get a few error messages relating to the timestamp:

```
Prototype mismatch: sub main::strftime ($\@;$) vs none at (eval 8) line 2.
Prototype mismatch: sub main::asctime (\@;$) vs none at (eval 8) line 2.
Prototype mismatch: sub main::ctime ($;$) vs none at (eval 8) line 2.
```

but it does print out in the format you required.
