### ISSUE TITLE
ReadLine::Stub

### ISSUE THREAD

**Issue by edison23** [oysttyer/oysttyer#43]
So, I'm not even sure this is an issue, it may be just my stupidity (if so, consider this issue a call for help, thanks).

Lately both oysttyer and old ttytter inform me on startup that they're using ReadLine::Stub and the consequence is (I presume) that I can't use the character counter, cannot move in the text while composing a tweet (e.g. "left" key inserts `^[[C` instead) and so on. As my perl-fu is below zero, may I ask what to do with this?

might-be-useful info:
- I'm not rly sure the readline ever worked properly with oysttyer, but it did with ttytter before
- oysttyer behaves exactly the same on a remote server with totally different linux distro
- perl version:

```
perl --version
This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 41 registered patches, see perl -V for more detail)
```

**Comment by atomicules** [comment]
Normally happens when you've upgraded (perhaps unintentionally?) the 
perl you are using and you need to reinstall the TTYtter readline.

Excuse brevity.

**Comment by edison23** [comment]
oh.. thanks, i totally forgot about that. But - i've installed `Term::ReadLine::TTYtter` via `cpan`, but it still doesnt work (uses ReadLine::Stub); is there be any other obvious config i need to do?

edit: after install, there was a test of the new module and it looked like it was working (character counting and left/right movement in the text worked)

**Comment by classilla** [comment]
Are you sure the Perl you installed it under is the same Perl running TTYtter/oysttyer?

**Comment by edison23** [comment]
pretty much, here's why:
I cloned oysttyer fresh (deleted it some time ago accidentally, I think), when tried to run it, got `/usr/bin/env: perl -s: No such file or directory` so I took the path I got from `which perl` and put it the shebang (hope I'm using the term right, TBH, I've seen it for the 1st time today xD) of the oysttyer script: `#!/usr/bin/perl -s`. After that oysttyer runs fine, except for the readline. 
As for this hack with path - never needed to do it before actually, so.. dunno, maybe connected?

edit: I seem to have set the `$PERL_RL` var to `TTYtter`, that's correct, right?

**Comment by classilla** [comment]
The environment variable is correct. The `perl -s` error indicates you seem to be bitten by what I warned about in pull #39. More to the point, I think you do have two separate Perls here.

What happens when you do `/usr/bin/perl -MTerm::ReadLine::TTYtter` ? If it's installed correctly, you should get something like `Can't locate object method "Features" via package "Term::ReadLine::Stub" at /usr/opt/perl5/lib/site_perl/5.8.8/Term/ReadLine/TTYtter.pm line 98.` If it's not, you'll get `Can't locate Term/ReadLine/TTYtter.pm in @INC`. If the latter, you need to start searching for another Perl.

**Comment by edison23** [comment]
OK, got the 2nd error, so I've used `whereis -b perl`, that gave me another location - `/usr/bin/X11/perl`. When tried `/usr/bin/X11/perl -MTerm::ReadLine::TTYtter`, got the same error - `Can't locate Term/ReadLine/TTYtter.pm in @INC`

I feel very newby and lost here, grh. Totally clueless as how to go on from here.

**Comment by atomicules** [comment]
What is your output from `cpanm -V`?

**Comment by edison23** [comment]
```
$ cpan -v
/usr/bin/cpan script version 1.61, CPAN.pm version 2.00
```

**Comment by atomicules** [comment]
Sorry, I meant `-V` (capitial V). You should be able to see which 
version of perl it is using and where it is looking for perl libraries 
(`@inc`).

**Comment by edison23** [comment]
oh.. sorry, haven't noticed the capital 'v' as there was the typo.. a/w, seems there's something definitely totally wrong (obviously permissions, but why? I haven't touch any perl config I think xD)

```
$ cpan -V
/usr/bin/cpan script version 1.61, CPAN.pm version 2.00
--------------------------------------------------
Checking install dirs...
Checking core
    !!! (not writeable) /usr/share/perl/5.18
    !!! (not writeable) /usr/lib/perl/5.18
Checking vendor
    !!! (not writeable) /usr/share/perl5
    !!! (not writeable) /usr/lib/perl5
Checking site
    !!! (not writeable) /usr/local/share/perl/5.18.2
    !!! (not writeable) /usr/local/lib/perl/5.18.2
Checking PERL5LIB
    no directories for PERL5LIB
Checking PERLLIB
    no directories for PERLLIB
--------------------------------------------------
Checking configured mirrors...
    + (  27 ms) http://cpan.mirror.euserv.net/
    + (  29 ms) http://www.planet-elektronik.de/CPAN/
    + (  43 ms) http://mirrors.teentelecom.net/CPAN/
--------------------------------------------------
Checking for faster mirrors...
Trying to fetch a mirror list from the Internet
Fetching with LWP:
http://cpan.mirror.euserv.net/MIRRORED.BY

Can't use string ("Europe") as an ARRAY ref while "strict refs" in use at /usr/share/perl/5.18/CPAN/Mirrors.pm line 142.
```

So I randomly tried:

```
$ ls -la /usr/share/perl/5.18
lrwxrwxrwx 1 root root 6 2015-09-03 06:49 /usr/share/perl/5.18 -> 5.18.2/
$ ls -la /usr/local/share/perl
ls: cannot access /usr/local/share/perl: No such file or directory
```

**Comment by atomicules** [comment]
I missed that you tried `cpan` originally. Try `cpanm -V` (as in version output from cpanminus). 

But, anyway, it does say you have "no directories for PERL5LIB" and the same for PERLLIB. It could just be that Perl can't find the things cpanm is installing. 

I have the following environment variables defined in my shell rc file. I'm guessing you are going to need something similar:

```
 PERL5LIB=/home/me/perl5/lib/perl5/x86_64-netbsd-thread-multi:/home/me/perl5/lib/perl5
```

I have cpanm install stuff local to my home directory, I _think_ by using these environment variables:

```
PERL_LOCAL_LIB_ROOT=/home/me/perl5
PERL_MM_OPT=INSTALL_BASE=/home/me/perl5
```

I can't remember where I picked up that configuration from though.

**Comment by edison23** [comment]
Thank you, the path to PERL5LIB did the trick, perl obviously didnt know where to find cpan's stuff. 

And sorry for the delay, a/w, solved, closing. Thank you all.
