### ISSUE TITLE
Pressing "end" on Term::ReadLine::TTYtter

### ISSUE THREAD

**Issue by IvanSanchez** [oysttyer/oysttyer#46]
This is more a question for @classilla than a bug in oysttyer...

I'm slightly annoyed by a lack of functionality in T:RL:T; namely, when pressing the "end" key, the cursor won't jump to the end of the line.

This is weird, because pressing "home" will jump to the beggining of the line, and pressing Ctrl+`E` will jump to the end.

So, where should I report a bug in T:RL:T?? Are there any plans to turn T:RL:TTYtter into T:RL:oysttyer?

**Comment by classilla** [comment]
Answering the second question first: T::RL::T is Perl license, so feel free to fork it, but I still maintain T::RL::T for my own projects.
As far as the End key, I'll look at it, though I'm trying to make relatively infrequent updates so I'll store this up for the next release.

**Comment by atomicules** [comment]
Pressing the end key works for me, so I guess this is one of those 
annoying differences between terminals, etc.

**Comment by funnelfiasco** [comment]
I'm going to close this because it's a Term::ReadLine::TTYtter issue and we have no plans on forking that any time soon.
