### ISSUE TITLE
/usr/bin/env: perl -s No such file....

### ISSUE THREAD

**Issue by dziq** [oysttyer/oysttyer#47]
Hello, 
I've just cloned oysttyer but I can't run it. I have:
/usr/bin/env: perl -s: No such file or directory
Any hint?

**Comment by funnelfiasco** [comment]
You can either change the first line to be:

```
#!/usr/bin/perl -s
```

Or invoke oysttyer as an argument to perl:

```
perl ./oysttyer.pl
```

Whichever shebang we use, it's apparently not going to work for some
people.

I've started a User Guide  (http://oysttyer.github.io/docs/userGuide.html)
which may be of help as well.

**Comment by atomicules** [comment]
See #39 for further discussion.

Personally, my bullet-proof solution is to just do:

```
perl /path/to/oysttyer.pl
```

**Comment by dziq** [comment]
Ok, thanks for quick reply. I've changed oysttyer.pl to:

 #!/usr/bin/perl -s

**Comment by Llammissar** [comment]
I think the "correct" solution may be to discontinue use of the -s switch entirely and move to Getopt::Long-- the current option parsing and setup is awfully hairy, IMO.  It's a tedious thing, though.

**Comment by atomicules** [comment]
Finally started looking into this properly and I think I'm with @Wyatts in that if we want to use `/usr/bin/env` then we will need to move to using Getopts::Long. I'll open a separate issue for that. In the meantime I'll rollback to what TTYtter used.

**Comment by atomicules** [comment]
Forgot to say that the problem with `/usr/bin/env perl -s` is that it's not valid syntax. We can have `/usr/bin/env perl` or `/usr/bin/perl -s`, but not "both".
