### ISSUE TITLE
Expand "video" urls

### ISSUE THREAD

**Issue by bartbes** [oysttyer/oysttyer#49]
I've noticed that tweets with video in them link to the thumbnail. Maybe it would be nice replacing the link with a link to the actual video?

For reference, the thumbnail url looks like: `https://pbs.twimg.com/tweet_video_thumb/<id>.png`
and the corresponding video is: `https://pbs.twimg.com/tweet_video/<id>.mp4`

As for downsides, people without mp4 playback support in their browsers won't be able to see the video play, whereas before they'd at least be able to see the thumbnail.

**Comment by IvanSanchez** [comment]
This should be easy to do as an extension (similar to deshortify, which already modifies inline links).

Can you please `/dump` a tweet with video, to make sure of how the internal structure looks like?

**Comment by funnelfiasco** [comment]
I'd vote for it being in the core. Giving a link to the thumbnail is
probably not the right default behavior, even for a CLI-based client.

**Comment by bartbes** [comment]
Here's a dump:

```
user->screen_name         crank_gaming
retweeted_status->id_str  685813810037403649
user->geo_enabled         false
place->id                 
place->country_code       
place->full_name          
place->place_type         
tag->type                 
tag->payload              
geo->coordinates          ()
contributors              
coordinates               
created_at                Sat Jan 09 13:35:14 +0000 2016
favorite_count            0
favorited                 false
id                        6.85817106433229e+17
id_str                    685817106433228800
in_reply_to_screen_name   
in_reply_to_status_id     
in_reply_to_status_id_str 
in_reply_to_user_id       
in_reply_to_user_id_str   
is_quote_status           false
lang                      en
menu_select               zb7
possibly_sensitive        false
retweet_count             10
retweeted                 false
source                    <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>
text                      RT @aeonofsands: More spells! Double #screenshotsaturday treat. And this time, the rat killed me.. @visionvortex #indiedev #gamedev https://pbs.twimg.com/tweet_video_thumb/CYSABmCWYAANJQf.png
truncated                 false
```

**Comment by atomicules** [comment]
I can pick this up, should be pretty straight-forward.

**Comment by funnelfiasco** [comment]
@atomicules I have something ready to go for this, but I don't want to step on you if you're working on something. Let me know if you want me to push my change or hold off.

**Comment by atomicules** [comment]
I almost have something to go as well. Sorry have been really busy as 
of late. I ended changing a lot of `destroy_all_tco`. If you can give 
me a day or two I'll get it pushed up.

All the code changes are done, I just need to do the commit message, 
but I want to write a proper one.

**Comment by funnelfiasco** [comment]
Works for me. I was going to do something a bit hackish like I did for the `:large` image URLs, so I look forward to seeing your implementation.
