### ISSUE TITLE
Support more than 140 characters in direct messages

### ISSUE THREAD

**Issue by atomicules** [oysttyer/oysttyer#5]
Seeing as how that is now a thing. Although:
1. I don't know for sure if there is a hard limit on TTYtters side of things
2. I don't want too many displayed anyway, let alone sent so need to think about truncating

**Comment by atomicules** [comment]
It'd be nice to be able to invoke $EDITOR to compose longer messages. I plan on having a look at TexApp and seeing if there is anything in there we can pull back into TTYtter.

**Comment by funnelfiasco** [comment]
We support sending 140+ character DMs now. Does it make sense to close this issue and open a separate issue for invoking $EDITOR?

**Comment by atomicules** [comment]
@funnelfiasco Ok, yeah, I'll open a new issue for that.
