### ISSUE TITLE
sponsored tweets?

### ISSUE THREAD

**Issue by cwage** [oysttyer/oysttyer#51]
I recently switched from ttytter and have noticed the appearance of sponsored tweets in my timeline along with the change.

I am guessing twitter is just delivering these like any other tweet, but I never got them in ttytter -- any way we can undo that, uh .. "feature"?

**Comment by atomicules** [comment]
Interesting. I've not seen them myself. That could well be an 
arrangement TTYtter had in place or perhaps it is a recent change for 
third party clients?

There is no way we could incorporate filtering of  sponsored tweets in 
oysttyer, we already seem to suffer Twitter's wrath. It may well be 
possible for someone to write an extension for oysttyer that could 
filter sponsored tweets, but, again, I don't think the oysttyer 
organisation could host it.

Just a thought, are you sure it is sponsored tweets you are seeing and 
not quoted tweets? A feature we did implement in oysttyer.

**Comment by funnelfiasco** [comment]
I, too, haven't noticed them, but we might not call them out as sponsored tweets. @cwage, can you do a `/dump _id_` on one and share that? I believe hiding them would violate the Rules, but it might be worthwhile to call them out as sponsored. (If nothing else, that would be useful for anyone who would write a totally unofficial plugin to filter them out).

**Comment by cwage** [comment]
```
user->screen_name         lenovoUS
retweeted_status->id_str  
user->geo_enabled         false
place->id                 
place->country_code       
place->full_name          
place->place_type         
tag->type                 timeline
tag->payload              stream
geo->coordinates          (, )
created_at                Fri Jan 15 20:26:17 +0000 2016
id_str                    688094877653929984
in_reply_to_status_id_str 
menu_select               j9
quoted_status_id_str      
retweet_count             0
source                    <a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>
text                      What would your future of gaming look like? Here’s @FeliciaDay’s take: http://lnv.gy/1Rm9X7P  #GameState
https://amp.twimg.com/v/1d137014-2b37-40a6-ba7a-c2e67afdd1c9
-- %URL% is now https://twitter.com/lenovoUS/statuses/688094877653929984 (/short to shorten)
```

**Comment by cwage** [comment]
I'd be okay filtering them in a plugin (i already have a few plugins for filtering arbitrary content), but it's not clear to me that there's any indication that it was a sponsored tweet -- which is making me wonder why i never saw them in ttytter

**Comment by cwage** [comment]
actually on second thought it might be as simple as checking if quoted_status_id_str and retweeted_status->id_str are both empty?

**Comment by cwage** [comment]
anyways, not really an oysttyer issue at this point, I'll close and if I can get something working I'll dump it in a plugin

**Comment by atomicules** [comment]
I just did a full json dump of that tweet and you are correct, there 
doesn't seem to be any indication it is sponsored or promoted (at 
least at initial look).

**Comment by atomicules** [comment]
I would have thought that would just filter most things from your 
stream. 

Although the json dump for the individual tweet didn't show any fields 
that indicate it is promoted, etc, perhaps the json structure for the 
stream might be slightly different and give some indication.

But getting a reproducible example might be a bit fiddly.

**Comment by classilla** [comment]
> That could well be an arrangement TTYtter had in place

No, no such arrangement existed.
