### ISSUE TITLE
threading

### ISSUE THREAD

**Issue by edison23** [oysttyer/oysttyer#53]
Currently the behaviour of command `/th` is that it'll show all tweets ((preceeding in time) && (in the thread)) of the tweet the command `/th` is invoked on. _(sorry for such horrible german-ish sentence, I had to use brackets to make sure it's readable only one way xD)_

This means that if `/th` invoked on the first tweet of the thread, only the tweet itself is shown.

Now, when I open the same tweet on twitter web, I can see the whole thread (obviously). So, my question is - is this an API limitation, or would it be possible to implement showing of the whole thread as web interface does?

(One nicely threaded tweet for reference: https://twitter.com/sinigaidd/status/690252962069921792)

**Comment by funnelfiasco** [comment]
I think that's some special sauce that Twitter keeps to itself. The way OysTTYer handles threading is to look at the `in_reply_to_status_id_str` attribute. I'll see if there's a way to look "forward".

**Comment by funnelfiasco** [comment]
So I finally got around to looking into this further, and even in a full json dump, there's no reference to any replies. We could do something like get the replies to the user and see if any of them are in reply to the tweet in question, but that seems expensive and prone to failure (might be worth trying it out as an extension for a while and seeing if it is workable).

Apparently a lot of people have asked for this, which means Twitter will never implement it.

**Comment by edison23** [comment]
Obviously twitter has something we dont... I can see a possibility in parsing a web output (from lynx, for example), but even at this time of a night it seems to me like a bad idea... let's keep this one sealed. 

(also, I dont understand the invalid tag, but whatever, doesn't matter)
