### ISSUE TITLE
Adding blank lines in–between tweets?

### ISSUE THREAD

**Issue by nfshr** [oysttyer/oysttyer#54]
Is there a way to add blank lines in–between tweets for better readability? As of now oysttyer is pretty cluttered, as far as i'm concerned..

**Comment by funnelfiasco** [comment]
There's nothing to allow that currently, though it's a pretty trivial feature to add.

**Comment by nfshr** [comment]
Would be much appreciated.. thank you for answering.

**Comment by IvanSanchez** [comment]
I guess a temporary solution would be to add a newline character to the timestamp format string.
