### ISSUE TITLE
Append :large to twitter image URLs

### ISSUE THREAD

**Issue by trs80** [oysttyer/oysttyer#55]
Reading #49 reminded me that the default image URLs are resized versions, and the original can be accessed by appending :large to the URL. I often use OS X Terminal's quick look, which means I can't easily append it manually (unlike if I'd right-clicked opened in a browser).

**Comment by funnelfiasco** [comment]
That's a good idea. Shouldn't be too hard to enable as an option. I'm not sure we'd want it always on, but I'm open to that argument.

**Comment by trs80** [comment]
This only works for the for the first image when there are multiple; I think you need a `g` at the end of the regex.

**Comment by funnelfiasco** [comment]
You're absolutely right. That'll get fixed in the next push.

**Comment by trs80** [comment]
The regex needs a bit more tuning - \w+ doesn't match https://pbs.twimg.com/media/Ca1-To_W8AAREfj.jpg

**Comment by funnelfiasco** [comment]
I couldn't find a reference to what characters Twitter might put in a URL, so I just went with any-non-whitespace character. That should solve this for good (or until they change something else). Thanks for catching this.

**Comment by atomicules** [comment]
We could think about handling this in `destroy_all_tco` instead 
of regexing it. Somehow. As long as we can be sure that the media is 
an image as I'm guessing :large won't work on video thumbnails?

**Comment by trs80** [comment]
On Wed, 10 Feb 2016, atomicules wrote:

> We could think about handling this in `destroy_all_tco` instead
> of regexing it. Somehow. As long as we can be sure that the media is
> an image as I'm guessing :large won't work on video thumbnails?

It seems to work OK:

https://pbs.twimg.com/ext_tw_video_thumb/696860539570421760/pu/img/V1u2tvlb2hsw5mwF.jpg:large
https://pbs.twimg.com/tweet_video_thumb/CazIIg7UMAAUmVZ.png:large

**Comment by atomicules** [comment]
Ok, what we could try is at [this point](https://github.com/oysttyer/oysttyer/blob/11deaa16a94701eb340a0c492040dcffd9ac67d4/oysttyer.pl#L7319) in the code doing something like:

```
my $sizesuffix = "";
if ($largeimages) {
    $sizesuffix = ":large";
}
$urls = $urls . " " . $tempurls . $sizesuffix
```

But that is over-simplified as we only want to do that to image urls. 

So... thinking about this a bit more it will probably be more verbose than the current solution and we still might need a regex to at least match for a url that ends in `.png`, `.jpg`, etc.

Let's keep the current solution.
