### ISSUE TITLE
Show original tweet time of native RTs

### ISSUE THREAD

**Issue by trs80** [oysttyer/oysttyer#56]
People sometimes RT politicians tweets from years ago (usually when they espoused an opinion that would embarrass them today), but the timestamp oysttyer shows is of when the RT happened. Quoted tweets show the original time. So could you make native RTs show the time of the original tweet?

Examples:
Native RTs:

`r5> [2016-02-06 20:42:45] (x887) <%NewtonMark> RT @CeltThulu: User: pls fix abuse\nTwitter: favs are likes now\nUser: k but abuse?\nTwitter: tweets pop out now\nUser: abuse???\nTwitter: ALGORITHMIC TIMELINE` (tweet actually from 10:29am)
`r8> [2016-02-06 20:59:27] (x7765) <%NewtonMark> RT @actioncookbook: USERS: you're alienating the people who actually use your product\nTWITTER: likes are now florps\nUSERS: what\nTWITTER: timeline goes sideways` (tweet actually from January 6)

Quoted tweet (that was then natively RTed):

`s0> [2016-02-06 21:05:31] (x11) <"%NewtonMark> RT @botandy: new algorithm based timeline https://twitter.com/TheAmyRios/status/694250227209936896`
`s1> [2016-02-02  4:05:27] (x448) <↑+TheAmyRios> Write the saddest story you can using only 4 words` (tweet shows correct time)

**Comment by funnelfiasco** [comment]
I'd never noticed that, but that's definitely a bug. I'll take a look at it (or someone else will if I get distracted, which happens often)

**Comment by funnelfiasco** [comment]
This might be a little harder than I'd first thought, so I'm leaving this note for myself (or whomever) to save a little bit of time when it gets looked at again.

It seems when a tweet is retweeted, the created_at is the time the user retweeted it. What we _should_ be displaying is the 'retweeteted_status' => 'created_at' value. It shouldn't be too painful to do that conditionally, since we already know to decorate it.

**Comment by funnelfiasco** [comment]
@trs80 I just pushed what I think is a fix for this. Can you verify that you get the timestamps you expect now?

**Comment by atomicules** [comment]
Sorry about removing the label. I think I must have deleted the entire label instead of removing the label from the issue.

**Comment by trs80** [comment]
Yep, they're now showing as the correct past time.
