### ISSUE TITLE
Allow use of $EDITOR for composing long DMs

### ISSUE THREAD

**Issue by atomicules** [oysttyer/oysttyer#57]
(And perhaps long tweets should that ever become a thing :fearful: )

This is split out from #5. Plan is still to look at Texapp and see if they've done anything of use we could use.

**Comment by Llammissar** [comment]
It's not clear what the project position on modules is, but this seems like it would provide the necessary functionality: http://search.cpan.org/~jmates/Term-CallEditor-0.66/lib/Term/CallEditor.pm

**Comment by classilla** [comment]
To get this to work in Texapp, I implemented a hold command for the background which stored up posts until the background is "un-held" and just called the editor directly with a `system()` call, no module necessary. You can look at most of the code in `sub updatest`.

**Comment by atomicules** [comment]
@classilla Fab, thanks.

**Comment by atomicules** [comment]
The spike in CPU usage I'm seeing isn't related to the editor directly. Maybe not at all? I can just start oysttyer up and not even use $EDITOR and after a while Perl is pegging 100% cpu. Needs some investigation as to whether I really have broken something or not.

**Comment by atomicules** [comment]
I _think_ it has gone wrong after 2a08d0cdaec834c4c38bf18dd752654d08096e70.

**Comment by atomicules** [comment]
Although that doesn't tie-up with the comments I made on recent commits.

**Comment by atomicules** [comment]
Ok, so I've run each commit for an extended period of time and it seems it all went wrong (and stays wrong) with d827d6d064c97b9af58837cbe3f0fc196589e8d7. So I definitely need to spend more time looking to see if I've implemented/copied this correctly from Texapp.

**Comment by atomicules** [comment]
I've been running these $EDITOR changes for a while now and I'm no longer seeing any CPU spiking or pegging. <embarrassed>I _think_ it was because of the userstream endpoint issue #74</embarrassed>, but I'm going to keep running them for awhile longer to make sure.
