### ISSUE TITLE
Block retweets or at least show them in a different color

### ISSUE THREAD

**Issue by sesom** [oysttyer/oysttyer#65]
In my desktop (Tweetdeck for Chrome) and mobile client (Tweetings for Android) I blocked retweets. I simply don't want to see them and there are too much of them. Is there a possibility in oysTTYer to do the same? Or at least show them in a different color?

Documentation is a bit thin about filtering. Is there on overview?

**Comment by edison23** [comment]
You can block all retweets or retweets from a certain user in Twitter settings on the web, I believe, so there is no need to have that ability in the client. Correct me if I'm wrong, tho.

**Comment by atomicules** [comment]
`-nonewrts` might do it. Are you looking at the Oysttyer documentation 
or the old TTYtter docs? We still need to move a lot of that over / 
re-write, etc.

**Comment by sesom** [comment]
@atomicules Thanks, -nonewrts does the job. When I'm back from travelling I can offer some time to help with the documentation.

@edison23 That is true in theory. First, it is a pain to do that for every single user you're following. Second, it does not work properly, sometimes RTs come through.
