### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by kuh3h3** [oysttyer/oysttyer#70]
of cource my account is ok , token is ok.  i used  well.
suddenly Json error occurred.

~]$ perl /home/reandr/oysttyer.pl -dostream -vcheck -verbose=1
-- termios test: POSIX::Termios=SCALAR(0x9fc3e18)
*\* attempting to load extensions
*\* loading /home/reandr/oysttyer-multigeo/multigeo.pl
-- Loading MultiGeo extension
-- Will not use GPSD
-- Will not use GeoIP
-- No geocoder specified, falling back to OpenStreetMap's Nominatim.
-- Will use the OpenStreetMap geocoding service, Nominatim. Geolocation data is CC-by-sa OpenStreetMap contributors. Have a look at http://wiki.openstreetmap.org/wiki/Nominatim
-- using SSL for default URLs.
trying to find cURL ... /bin/curl
-- Streaming API enabled
-- checking oysttyer version: https://raw.githubusercontent.com/oysttyer/oysttyer/master/version_check.txt
-- server response: oysttyer;2.6.1;;;https://raw.githubusercontent.com/oysttyer/oysttyer/2.6.1/oysttyer.pl;
--**--
--**--
--__--

-- your version of oysttyer is up to date (2.6.1)
(checking credentials) test-login SUCCEEDED!
-- processing credentials: **\* JSON syntax error
--- data received ---
¼VMÛ6ý+¯ul}ÛP$H6AN-XÑ ¥Í,E_$eg³ðïÐ²¼òÚÛ 9ÔðoÞÌofH=RQÑ|ó$²  ®uætè_Þ'¸ª
                                                                                               iySSQQ0´¥PìÌfºäNh ®_@hÀ§Ká qä^7#[­Ç§ÄªHÃ$Nc@ÂÙ8×æÅ¬¹i©Ùí:nc÷éï¯?0~g$ÍUSSQQ0årÂ   °4<OûèyìéôßÂ÷CÅQ×~cHoü¡m%8RÆ¡_Qú-|Iyx·¿ÛïSSQQ0´5ÚAé®¹´0¡µRïÀXVêN9óQ#P¶c=¤°è8@HBÙ¹G8.é_'è-   SDyæiJ~
°Zùb~ä;.z¯A3P|%G[ßµÖq×Ù§Iâ¶¹Zc$Pt ø:íýó¦#!  â<
¸Ú&èÕ÷õÛãk?]wX f¥åqq8]ãÉZõþÒaÀÍÐO3å5Lv0Yà\OKånÿ´ñêùáFÈÓDìÏuº0Ì®¬äh¾â!/ð©¶âåýÚ ~þÎÞ¾¹ãyö³>ê×wÁ®ÔÚTB¡Rvp¼N]9#VÓæD}ëpØÐG
                                                                                                          nÞ¿¿¡W9¢ákx~×µ+;ÅönÖæ½äfY%ñ|dÅlÇ¥ly
                                                                                                                                                  æUñ?ýÚ®ùöØþ®i³>Òë0äN³E-æaZÌÂx¥IDSÚ4øµjýû
                                           Y¤P÷§rÁ'y¬VT°â­pvqL^l
                                                                      ybÝ éC6bùûõd¿ñ¢Zä8¿
                                                                                             áð¼Ný[Aßîgøñì~²Î¼Ô¾u`Ão
w²)íðéê?O{hÿÿÿ³&ßÆ  
--- syntax tree ---
¼VMÛý+¯ul}ÛP$HAN-XÑ ¥Í,E_$eg³ðïÐ²¼òÚÛ ÔðoÞÌofH=RQÑ|ó$²®uætè_Þè-SDyæiJ~ðG¢Xâj¾ÕNQ#ÍL×µ\¾¤O¨°Zùb~ä;.z¯AP|%G[ßµÖq×Ù§Iâ¶¹Zc$Ptø:íýó¦#!â<òtyÚ{zG,(¢Q§QjÑK#zøî£¿¹Õ²n¸ï$×õÑïaZùÀf½RÌ¼ïé«Æþô,øfQâ«ÆA¹ãyö³>ê×wÁ®ÔÚTB¡Rvp¼N]#VÓæD}ëpØÐG¸Ú&èÕ÷õÛãk?]wX f¥åqq]ãÉZõþÒaÀÍÐOåLvYà\OKånÿ´ñêùáFÈÓDìÏuºÌ®¬äh¾â!/ð©¶âåýÚ ~þÎÞ¾nÞ¿¿¡W¢ákx~×µ+;ÅönÖæ½äfY%ñ|dÅlÇ¥lyæUñ?ýÚ®ùöØþ®i³>ÒëäN³E-æaZÌÂx¥IDSÚøµjýûY¤P÷§rÁ
--- JSON PARSING ABORTED DUE TO SYNTAX TREE FAILURE --
FAILED!
is your account suspended, or wrong token?

**Comment by atomicules** [comment]
Does the same error occur with 2.6.0?

Just trying to work out if I/we have broken something at what point 
that happened.

**Comment by kuh3h3** [comment]
just download 2.6.0. same error. maybe my recent fedora 22  updated json-releated perl. how to check json-related package?

**Comment by atomicules** [comment]
Sorry for the delay in replying.

On 15-Mar-2016 06:10:53, kuh3h3 wrote:

> just download 2.6.0. same error. maybe my recent fedora 22 system updated json-releated perl.

One way to confirm for sure is to try with the last release of TTYtter 
and see if you still get the error there.

**Comment by kuh3h3** [comment]
thanks . i closed this issue.

**Comment by atomicules** [comment]
Maybe related to versions of curl. Try `--compressed` on curl's flags.
