### ISSUE TITLE
Migrating from ttyter

### ISSUE THREAD

**Issue by Jzarecta** [oysttyer/oysttyer#78]
I am migrating to oyster, so I wonder if I can just softlink my .ttyterrc to .oysttyerrc and expect to perform as expected or are the conf files that different that I should re-generate my dotfile from scratch.

**Comment by atomicules** [comment]
I think most things have stayed the same. The only one I can think of 
that has definitely changed is that `ttytteristas` is now called 
`oysttyeristas`. Also there are some new options provided under 
oysttyer. But in general, yeah, soft linking should work fine.
