### ISSUE TITLE
/short stopped working

### ISSUE THREAD

**Issue by ghost** [oysttyer/oysttyer#79]
The URL shortener stopped working. Whenever I try to shorten a URL I get an error:

> oysttyer> /short https://github.com/oysttyer/oysttyer/ <027
> **\* shortened to: FAILED -- %% to retry

The API for is.gd has changed, but the old request format still works.
Changing the `$shorturl` variable according the actual API reference doesn't help.

vcheck:

> -- your version of Term::ReadLine::TTYtter is up to date (1.4)
> -- your version of oysttyer is up to date (2.7.0)

**Comment by atomicules** [comment]
Thanks for the report: I don't think I've ever used that functionality 
myself so I wouldn't have noticed.

I will take a look.

**Comment by atomicules** [comment]
Hmmm, tried to test, but since I run Oysttyer on a server (Linode) I 
unfortunately get "Your network address is banned from shortening 
URLs..."

All I did was changed line 742 to:

```
$shorturl ||= "https://is.gd/create.php?format=simple&url=";
```

It didn't work, so I tested from the command line:

```
curl -s -m 20 "https://is.gd/create.php?format=simple&url=https%3A%2F%2Fgithub.com%2Foysttyer%2Foysttyer%2F"
```

And got the ban error. I tested locally and it shortened fine 
(https://is.gd/Rdcy6t) So I presume that Oysttyer would also work 
fine locally with the above change. No time to try today though.

I don't suppose you are seeing a server ban as well?

I guess a proper fix for this needs to report the error message, etc.

**Comment by vitusson** [comment]
I ran into the same problem yesterday, and fixing the $shorturl line didn't work.
Though it works with the curl command in a shell....

Even with superverbose=1 all I got in oysttyer was

> vitusson> /short `https://github.com/oysttyer/oysttyer/issues/79#issuecomment-224096384` <076  
> /usr/bin/curl -s -m 20 "https://is.gd/create.php?format=simple&url=https%3A%2F%2Fgithub.com%2Foysttyer%2Foysttyer%2Fissues%2F79%23issuecomment-224096384"
> **\* shortened to: FAILED -- %% to retry

**Comment by ghost** [comment]
> I presume that Oysttyer would also work fine locally with the above change.

Nope.

The new API call works fine from CLI (not the old one any more):

```
$ /usr/bin/curl -s -m 20 "https://is.gd/create.php?format=simple&url=https%3A%2F%2Fgithub.com%2Foysttyer%2Foysttyer%2Fissues%2F79"
https://is.gd/1fWwGl
```

Unfortunately, it does not work in oysttyer, even when running locally (superverbose):

```
oysttyer> /short https://github.com/oysttyer/oysttyer/issues/79-- select pending (53 sec left)

-- select pending (51 sec left)
-- select pending (51 sec left)
-- calling $addaction in /home/user/.ttytter-extensions/where.pl
-- calling $addaction in /home/user/.ttytter-extensions/info.pl
-- calling $addaction in /home/user/.ttytter-extensions/mark.pl
-- calling $addaction in /home/user/.ttytter-extensions/report.pl
/usr/bin/curl -s -m 20 "https://is.gd/create.php?format=simple&url=https%3A%2F%2Fgithub.com%2Foysttyer%2Foysttyer%2Fissues%2F79"
*** shortened to: FAILED -- %% to retry
oysttyer> -- select pending (51 sec left)
```

> I guess a proper fix for this needs to report the error message, etc.

Just tell me, what you need to resolve it.

**Comment by atomicules** [comment]
Thanks for checking that. A fix is now up on master. Not closing this 
issue out yet though as a full fix really needs to return an error 
message (unless that proves too fiddly to do, but I'd at least like to 
take a look).

**Comment by ghost** [comment]
The shortener works again, thanks.
