### ISSUE TITLE
/replyall erroneously appends tweetId to reply

### ISSUE THREAD

**Issue by Llammissar** [oysttyer/oysttyer#80]
Seems to happen with conversations and RTs.  Random example I just grabbed to demonstrate:

```
k8> <↑MSNBC> .@POTUS: "Enough talking about being tough on terrorism... actually be tough on terrorism."  http://nbcnews.to/1URx4mG
oysttyer> /replyall k8 foo bar <020
-- verify you want to tweet: "@MSNBC @POTUS foo bar 742757246728183808"
```

And yes, as I've discovered, that _will_ come out in the resulting tweet.

I looked at the code, but it's really not obvious to me why this is happening.

**Comment by funnelfiasco** [comment]
What version are you seeing this with? I haven't been able to reproduce the error.

**Comment by atomicules** [comment]
I could see that maybe coming from the quote tweet stuff - somehow, 
but also I'm not exactly sure how.

**Comment by Llammissar** [comment]
Oh good lord, I figured the problem out.  I still had the old r2a.pl extension loading because I changed the wrong rcfile.  (Yes, I'm STILL getting used to the new name.)  Sorry for the false alarm.

I do wonder if there's a way this could have been avoided, though...? (i.e. warn/error if there's a conflict/overload)  Not sure how possible that is, though; prinput() uses regexen for choosing code path, and I'm not aware of a good way to test those for intersecting coverage.

**Comment by funnelfiasco** [comment]
As the author of the reply-to-all extension, I am pleased you found it useful and I apologize it broke oysttyer for you. :-) I stopped using the extension when it got pulled into mainline TTYtter.

I agree it would be nice if we could make it more obvious, but an extension conflicting with a built-in command is a desired behavior in some cases I would think. I'm not sure what the right answer is here.

**Comment by classilla** [comment]
Yes, the original idea was that extensions could overload and replace built-in commands (except for ones like /quit, obviously). You'd probably have to have some declarative method for finding conflicts, but this wouldn't help for older extensions.
