### ISSUE TITLE
UTF characters are replaced with 2 character ascii combinations - may be Term::Readkey issue

### ISSUE THREAD

**Issue by gustafe** [oysttyer/oysttyer#84]
Issue: entering text with Swedish characters renders them in 2 char replacements.

Example: Räksmörgås becomes RC6ksmC6rgC%s

I believe this is an issue with Term::Readkey as this worked in Ttytter before. I installed Oysttyer and Term::readkey yesterday as part of my migration off TTytter but have encountered this today.

The same issue now appears in Ttytter.

As a workaround I can live with disabling the Term::Readkey support. As a last resort I'll uninstall it.

**Comment by funnelfiasco** [comment]
Sorry for the late response. Looks like the last Term::Readkey release was in June of 2015. You could try rolling back to an older version. It doesn't look like oysttyer directly calls Term::Readkey anywhere, so I don't know if there anything we can do to work around it.
