### ISSUE TITLE
Hacktoberfest?

### ISSUE THREAD

**Issue by funnelfiasco** [oysttyer/oysttyer#88]
People who want to [earn a t-shirt](https://hacktoberfest.digitalocean.com/) should do it by submitting PRs to oysttyer. One way to make it easier for them to find is to create a Hacktoberfest label and slap that on issues.

I was thinking it might be nice to create issues for a few things we want to add (e.g. image size as a single option instead of a bunch of booleans) and put the Hacktoberfest label on them. On the other hand, I know @atomicules really wants to refactor the code, so maybe it's best not to solicit a bunch of new additions.

**Comment by atomicules** [comment]
I wouldn't really say I have a burning desire to refactor, it's just that if we want more people to help then it needs cleaning up. The code base is off-putting (it's also half the attraction for me, but I'm not normal).

**Comment by atomicules** [comment]
But this is a good idea. I've been trying to label stuff easier/harder so newcomers could pick issues up.
