### ISSUE TITLE
Cannot redirect tweets

### ISSUE THREAD

**Issue by Azenet** [oysttyer/oysttyer#90]
Hi,

Please note that I searched for an argument that would allow this but I didn't find a compromise, I hope I haven't overlooked something.

I'd like to use oysttyer to redirect my timeline, however I didn't find any argument that would allow it. My attempt is to run `oysttyer | tee file` so I can both see what's happening and maybe tweet, and redirect the content. However, when in this mode, tweets do not appear by themselves, I have to type /again for them to appear, that seems to be done without any API request since it is instantaneous. I am running in stream mode.

Here's my oysttyerrc:

```
readline=0
dostream=1
ansi=0
timestamp=%d-%m %k:%M:%S
verify=1
```

Related to #82 (maybe duplicate, even)

**Comment by funnelfiasco** [comment]
Yeah, I don't think there's a good way to redirect and have it still be usable interactively. If you want to tweet (not reply or RT), you can invoke it separately:

`oysttyer -status='Hey @mscman, remember to take the trash to the curb tonight'`

If you just want to preserve tweets for the record, you can use the pwntter extension: https://github.com/pr4wn/ttytter-exts/tree/master/pwntter

I haven't tried pwntter with oysttyer, but from a quick look at the code, it should be compatible.

**Comment by Azenet** [comment]
Unfortunately the extension is not cutting it for me, the reason I wanted to log the client output directly is because it fetches e.g. the quoted tweets, and other fluff.

I could do without the interactivity though, would there be any way to disable that ?

**Comment by funnelfiasco** [comment]
The `-daemon` argument will disable it. It will say `Terminated` after you launch, but the background process will continue to display the timeline until you `kill` it. For example:

```
[1049 bcotton@normal ~ ]$ devel/oysttyer/oysttyer.pl -daemon | tee timeline.txt
Terminated
[1050 bcotton@normal ~ ]$
```

The output will include `*** detached daemon released. pid = 6369` so you can find the PID to kill when you're done.

**Comment by Azenet** [comment]
Thank you! I didn't try it because I thought it would detach, but this is perfect.

**Comment by vitusson** [comment]
I use the log extension to redirect my timeline to a logfile since ages, works with oysttyer same as it did with ttytter.
Cant find the source for it, once there was a link on the old ttytter

#$extension_mode = $EM_SCRIPT_OFF;

$handle = sub {
        my $ref = shift;
        my $logfile = "/$path_to/timeline.log";
        my $tweet2 = &descape($ref->{'text'});
        my $stweet2 = &standardtweet($ref);
        open(S, ">>", $logfile) || # combine strings for 5.005
                die("can't open $logfile for append: $!\n");
        binmode(S, ":utf8") unless ($seven);
        print S $stweet2;
        close(S);
        &defaulthandle($ref);
        return 1;
};

**Comment by Azenet** [comment]
It seems like using `-daemon` disables streaming even though it says "Streaming API enabled" when starting up, is this expected? It's fetching regularly and I'm not getting usual favorites/retweets notifications. I'm using 0841d20

**Comment by funnelfiasco** [comment]
Works for me

```
>>> @hacklafayette just liked @FunnelFiasco's tweet: "Vero Beach still flirting with that 74 MPH number. #Matthew"
g0> <%Glinner> RT @NomadicWriter: @Glinner Anybody who saw the effects of trauma and difficult decision she's made wouldn't hesitate over this issue. My heart broke for her.
>>> @hacklafayette just unliked @FunnelFiasco's tweet: "Vero Beach still flirting with that 74 MPH number. #Matthew"
```

I'm one commit ahead of you (that I just pushed), but that change shouldn't affect anything. If you're still seeing this, can you open a new issue and share your settings?
