### ISSUE TITLE
Stream not working with daemon

### ISSUE THREAD

**Issue by Azenet** [oysttyer/oysttyer#94]
`daemon` seems to break streaming on my end. I am not sure if this is actually related to `daemon` though, as I am sometimes using 2 oysttyer instances on the same token, I guess rate limiting could be the cause, but I cannot see why it should stop streaming. I'm using 2a1600162285aaaf465f92ea1fe6533a86da0837, but this was happening before (also on 0841d207f97b5d93ee5367ae52186c8049f74d20).

`.oysttyerrc`:

```
readline=0
extended=1
origimages=1
dostream=1
ansi=0
timestamp=%d-%m %k:%M:%S
verify=1
daemon=1
```

**Comment by funnelfiasco** [comment]
I just tested with your settings and I'm still getting streaming. I'll leave this issue open for a little bit in case someone else can reproduce the behavior. If you use the same setup but without daemon mode, do you get the expected behavior?

**Comment by Azenet** [comment]
Yes, it works without daemon mode.

**Comment by Azenet** [comment]
I was watching it run and I found something, I actually AM getting the streaming notifications like "someone liked your tweet" etc, it is just not displayed instantly. Everything seems to stay in a buffer and this buffer would be flushed every minute.

**Comment by funnelfiasco** [comment]
The streaming API is dead, so I guess there's nothing to do about this bug.
