### ISSUE TITLE
Only one picture is displayed where there should be several

### ISSUE THREAD

**Issue by Azenet** [oysttyer/oysttyer#95]
Hi,

There seems to be a regression from 2.7.2, /th 785576798235090944 should display 2 pictures instead of 1. I'm using 2a1600162285aaaf465f92ea1fe6533a86da0837. The regression seems to come from commit 0841d207f97b5d93ee5367ae52186c8049f74d20.

**Comment by funnelfiasco** [comment]
So it does. I made that change to fix GIFs, but apparently it had some unexpected side effects. I'll see if I can find a better fix.
